# -*- coding: utf-8 -*-
"""
Detailed hexagram interpretations for all 64 hexagrams.
Each hexagram code (0-63) maps to a dict with:
  - overall: {title, desc} — general meaning
  - love/career/wealth/health/travel: {title, desc} — per-fortune in 5 languages
"""

def _p(zh_t, ja_t, en_t, vi_t, ko_t, zh_d, ja_d, en_d, vi_d, ko_d, my_t="", my_d=""):
    return {
        "title": {"zh": zh_t, "ja": ja_t, "en": en_t, "vi": vi_t, "ko": ko_t, "my": my_t},
        "desc":  {"zh": zh_d, "ja": ja_d, "en": en_d, "vi": vi_d, "ko": ko_d, "my": my_d},
    }

def _titles(zh, ja, en, vi, ko, my=""):
    return {"zh": zh, "ja": ja, "en": en, "vi": vi, "ko": ko, "my": my}

INTERPRETATIONS = {}

# ===== 1. 乾为天 (Qian) =====
INTERPRETATIONS[0] = {
    "overall": _p("乾为天","乾為天","Qian: The Creative","Càn: Sáng tạo","건: 창조",
        "乾卦六爻皆阳，象征纯阳至刚之力，代表天道运行、自强不息。此卦暗示你正处于能量充沛、志向远大的阶段，但也需警惕刚愎自用。核心在于'元亨利贞'——大通大利，但必须守正道。",
        "乾卦は六爻すべて陽であり、純粋な陽の至剛の力を象徴し、天の道の运行と自強不息を表します。",
        "Qian represents pure creative force — six solid yang lines symbolising heaven in ceaseless motion. You are in a phase of strong energy and ambition.",
        "Quẻ Càn gồm sáu hào dương thuần, tượng trưng cho sức mạnh sáng tạo thuần khiết và lòng tự cường không ngừng.",
        "건괘는 육효 모두 양으로, 순수한 양의 지극한 강함을 상징하며 끊임없이 운행하는 하늘의 도를 나타냅니다."),
    "love": _p("恋爱运势","恋愛運勢","Love Fortune","Vận tình cảm","연애운",
        "感情上处于主动而强势的地位。你的魅力和自信能吸引优质的对象，但要注意不要过于强势让对方感到压力。有伴侣者需要更多温柔与体贴，单身者桃花运旺盛，但要分辨真心与奉承。",
        "恋愛では主導権を握る立場にあります。魅力と自信で良い相手を引き寄せられますが、相手に圧力をかけすぎないようにしましょう。",
        "You hold the active position in romance. Your confidence attracts quality partners, but don't overwhelm them with dominance.",
        "Bạn đang ở vị trí chủ động trong tình cảm. Sự tự tin thu hút đối tượng tốt, nhưng đừng quá mạnh mẽ.",
        "연애에서 주도적인 위치에 있습니다. 매력과 자신감으로 좋은 상대를 끌어들이지만 너무 강세적일 경우 부담을 줄 수 있습니다."),
    "career": _p("事业运势","事業運勢","Career Fortune","Vận sự nghiệp","직업운",
        "事业发展势头强劲，适合开拓新领域或承担领导角色。执行力和决断力都很强，适合做重要决策。但要记住'亢龙有悔'——过于高调可能招致嫉妒。建议稳扎稳打，巩固已有成果再逐步扩张。",
        "事業の勢いは強く、新分野の開拓やリーダーシップの役割に向いています。重要な判断に適しています。",
        "Career momentum is strong — ideal for new ventures or leadership roles. Your execution and decisiveness are at their peak.",
        "Sự nghiệp đang trên đà phát triển mạnh mẽ, phù hợp mở rộng lĩnh vực mới.",
        "직업운이 강세입니다. 새로운 분야 개척이나 리더십 역할에 적합한 시기입니다."),
    "wealth": _p("财运","金運","Wealth Fortune","Vận tài chính","재운",
        "财运亨通，正财收入有明显增长的机会。适合做长期投资或购置固定资产。但不要贪大求全，一次性投入过多风险较大。建议分散投资，保持现金流充裕。",
        "金運は大きく開けており、本業の収入増が見込まれます。長期投資や不動産の購入に向いています。",
        "Wealth luck is strong with clear growth in regular income. Good time for long-term investments or property.",
        "Tài vận hanh thông, thu nhập chính có cơ hội tăng rõ rệt. Phù hợp đầu tư dài hạn.",
        "재운이 크게 열립니다. 정기 소득이 확실히 증가할 시기입니다."),
    "health": _p("健康运势","健康運勢","Health Fortune","Vận sức khỏe","건강운",
        "整体精力充沛，但要防止过度消耗。阳气极盛，容易出现上火、头痛、血压升高等阳亢症状。建议保持规律作息，适当做舒缓的运动如太极、瑜伽来平衡阴阳。",
        "エネルギーに満ちていますが、使い過ぎに注意。陽気が極めて盛んなため、のぼせや頭痛が起きやすい時期です。",
        "Overall energy is high, but guard against overexertion. Extreme yang can cause headaches or high blood pressure.",
        "Tổng thể tràn đầy năng lượng, nhưng đề phòng kiệt sức. Dương khí cực thịnh, dễ gây nóng trong, đau đầu.",
        "에너지가 넘치지만 과도한 소모를 주의하세요. 양기가 강해지면 두통이나 혈압 상승이 있을 수 있습니다."),
    "travel": _p("人际运势","人間運勢","People Fortune","Vận nhân tế","대인운",
        "人际关系中你处于中心位置，容易成为焦点。建议多倾听他人意见，不要一味输出自己的想法。出行方面，长途旅行或出差可能带来新的机遇。",
        "人間関係では中心的な位置にあり、注目を集めやすいです。相手の意見に耳を傾けましょう。",
        "You are central in social circles — listen more than you speak. Travel or business trips may bring fresh opportunities.",
        "Bạn ở vị trí trung tâm trong các mối quan hệ, dễ trở thành tâm điểm. Nên lắng nghe nhiều hơn nói.",
        "인간관계에서 중심에 있어 주목받기 쉽습니다. 남의 의견에 귀를 기울이세요."),
}

# ===== 2. 坤为地 (Kun) =====
INTERPRETATIONS[1] = {
    "overall": _p("坤为地","坤為地","Kun: The Receptive","Khôn: Tiếp nhận","곤: 수용",
        "坤卦六爻皆阴，象征柔顺、包容、厚德载物之象。当前宜以守为主，采取配合与接纳的态度。大地之德在于承载万物，你需要耐心、稳健和对环境的顺应。",
        "坤卦は六爻すべて陰であり、柔順・包容・厚徳載物を象徴します。今は受動的で協調的な姿勢が求められています。",
        "Kun is six yin lines — pure receptivity. Your role now is to support, nurture, and allow things to develop rather than forcing them.",
        "Quẻ Khôn gồm sáu hào âm thuần, tượng trưng cho sự mềm mại, bao dung. Bạn cần lấy thủ làm chủ, phối hợp và tiếp nhận.",
        "곤괘는 육효 모두 음으로, 순종과 포용을 상징합니다. 지금은 수동적이고 협조적인 자세가 필요합니다."),
    "love": _p("恋爱运势","恋愛運勢","Love Fortune","Vận tình cảm","연애운",
        "感情上更适合以柔克刚。温柔、体贴和包容力是最大的武器。有伴侣者通过默默关怀来加深感情，单身者可能在日常生活中遇到温柔可靠的对象。",
        "恋愛では以柔制剛が効きます。優しさ・気遣い・包容力が最大の武器です。",
        "In love, softness conquers. Your gentleness and tolerance are your greatest tools. Singles may meet someone warm and reliable.",
        "Trong tình cảm, dùng mềm thắng cứng. Sự dịu dàng và bao dung là vũ khí lớn nhất.",
        "연애에서는 유연함이 강점입니다. 부드러움과 포용력이 가장 큰 무기입니다."),
    "career": _p("事业运势","事業運勢","Career Fortune","Vận sự nghiệp","직업운",
        "事业上宜做好本职工作，不宜越级行事。当前角色是协助者和支持者，把细节做好、把基础打牢自然会获得认可。",
        "事業では自分の役割をしっかり全うし、権限を超えた行動は避けましょう。",
        "Do your current role well — avoid overstepping. Master details and build solid foundations.",
        "Nên làm tốt công việc hiện tại, không nên vượt quyền. Chú trọng chi tiết và nền tảng.",
        "현재 역할을 성실히 수행하고, 권한을 벗어나는 행동은 피하세요."),
    "wealth": _p("财运","金運","Wealth Fortune","Vận tài chính","재운",
        "财运平稳，适合积少成多的策略。不宜做高风险投资，以稳健理财为主。通过日常的节约和合理规划来增长财富。",
        "金運は穏やかで、少しずつ積み立てる戦略に向いています。ハイリスク投資は避けましょう。",
        "Wealth is steady — focus on gradual accumulation, not high-risk plays. Grow through daily saving and sound planning.",
        "Tài vận ổn định, phù hợp tích góp từ từ. Nên quản lý tài chính vững chắc.",
        "재운이 평탄합니다. 조금씩 쌓아가는 전략이 적합합니다."),
    "health": _p("健康运势","健康運勢","Health Fortune","Vận sức khỏe","건강운",
        "健康状况总体稳定，但需要关注消化系统和关节。坤卦属土，对应脾胃，容易出现消化不良、腹胀。建议饮食清淡、规律进食。",
        "健康は全体的に安定していますが、消化器関節と関節に注意。坤卦は土に属し、脾胃に対応しています。",
        "Health is generally stable, but watch your digestive system and joints. Kun belongs to earth, linked to the spleen and stomach.",
        "Sức khỏe ổn định, nhưng chú ý hệ tiêu hóa. Quẻ Khôn thuộc thổ, tương ứng tì vị.",
        "건강은 전반적으로 안정적이지만 소화기와 관절에 주의하세요. 곤괘는 토에 속하여 비위와 관련되어 있습니다."),
    "travel": _p("人际运势","人間運勢","People Fortune","Vận nhân tế","대인운",
        "人际关系上适合做倾听者和协调者。包容力能让周围的人感到安心。适合短途旅行或温馨聚会。",
        "人間関係では聴き手・調停者として適しています。包容力が周囲に安心感を与えます。",
        "Be the listener and mediator. Your inclusiveness makes others feel safe. Short trips or warm gatherings are favoured.",
        "Nên làm người lắng nghe và hòa giải. Sự bao dung giúp mọi người an tâm. Phù hợp du lịch ngắn ngày.",
        "경청자와 중재자 역할이 적합합니다. 포용력이 주변에 안심을 줍니다."),
}

# ===== 3-63: Generated from standard I Ching meanings =====
_HEX_DATA = {
    2: ("水雷屯","水雷屯","Zhun: Difficulty at the Start","Truân: Khởi đầu khó khăn","툰: 초반의 어려움",
        "屯卦象征初生之难，如同嫩芽破土而出。事情刚开始时总会遇到阻碍，关键是找到志同道合的人一起前行。",
        "屯卦は初生の困難を象徴し、芽が土を突き破るように艰辛しながらも生命力に満ちています。",
        "Zhun represents the difficulty of new beginnings — like a sprout breaking through soil. Persevere and seek allies.",
        "Quẻ Truân tượng trưng cho khó khăn ban đầu — như mầm non đâm qua đất. Cần kiên trì và tìm người đồng hành.",
        "툰卦는 시작의 어려움을 상징합니다. 새싹이 땅을 뚫고 나오듯 힘들지만 생명력이 가득합니다."),
    3: ("山水蒙","山水蒙","Meng: Youthful Folly","Mông: Trí não trẻ thơ","몽: 어리석음",
        "蒙卦象征蒙昧未开，需要学习和启蒙。当前你可能对某些事情还不够了解，需要虚心求教。",
        "蒙卦は未開の状態を象徴し、学びと啓発が必要です。謙虚に学ぶべきです。",
        "Meng signals ignorance that needs teaching. Be humble and seek guidance. Admitting gaps leads to growth.",
        "Quẻ Mông tượng trưng cho sự chưa khai sáng, cần học hỏi. Khiêm nhường cầu thị.",
        "몽卦는 미개의 상태를 상징하며, 배움과 계몽이 필요합니다. 겸손하게 배우세요."),
    4: ("水天需","水天需","Xu: Waiting","Nhu: Chờ đợi","수: 기다림",
        "需卦象征等待的智慧。事情时机尚未成熟，强行推进反而适得其反。你需要积蓄力量，等待最佳时机。",
        "需卦は待ちの知恵を象徴します。時期がまだ熟していないのに無理に進めると逆効果。力を蓄え、最良のタイミングを待ちましょう。",
        "Xu teaches the wisdom of waiting. The time is not yet ripe — accumulate strength and wait for the right moment.",
        "Quẻ Nhu tượng trưng cho trí tuệ của sự chờ đợi. Thời cơ chưa chín, cần tích lũy lực lượng.",
        "수卦는 기다림의 지혜를 상징합니다. 시기가 아직 무르익지 않았으니 힘을 비축하세요."),
    5: ("天水讼","天水訟","Song: Conflict","Tụng: Tranh chấp","송: 다툼",
        "讼卦象征争讼与冲突。告诫你不要轻易诉讼，以和为贵。退一步海阔天空，妥协比争赢更有利于长远发展。",
        "訟卦は争いと衝突を象徴します。軽率に争わず、調和を大切にしましょう。",
        "Song signals conflict. Avoid lawsuits if possible — harmony is precious. Stepping back often serves you better.",
        "Quẻ Tụng tượng trưng cho tranh chấp. Tránh kiện tụng nếu có thể — hòa thuận là quý.",
        "송卦는 다툼과 갈등을 상징합니다. 무리하게 다투지 말고 조화를 중요시하세요."),
    6: ("地水师","地水師","Shi: The Army","Sư: Quân đội","사: 군대",
        "师卦象征组织纪律和团队力量。成功的关键在于严明的纪律、正确的领导和明确的目标。学会借助团队的力量。",
        "師卦は組織紀律とチームの力の象徴です。成功の鍵は厳格な紀律、正しいリーダーシップ、明確な目標です。",
        "Shi represents disciplined teamwork. Success requires strict discipline, correct leadership, and clear goals.",
        "Quẻ Sư tượng trưng cho kỷ luật tổ chức và sức mạnh tập thể. Thành công đòi hỏi kỷ luật nghiêm minh.",
        "사卦는 조직 규율과 팀의 힘을 상징합니다. 엄격한 규율, 올바른 리더십이 성공의 열쇠입니다."),
    7: ("水地比","水地比","Bi: Holding Together","Tỷ: Kết hợp","비: 결합",
        "比卦象征亲比、团结和合作。主动伸出友谊之手，但也要看清对象——选择正直可靠的人合作。",
        "比卦は親密さ・団結・協力の象徴です。友誼の手を差し伸べますが、相手の正直さを見極めましょう。",
        "Bi means alliance and unity. Extend friendship actively, but choose honest and reliable partners.",
        "Quẻ Tỷ tượng trưng cho sự thân thiết, đoàn kết. Chọn người thẳng thắn đáng tin.",
        "비卦는 친밀함과 단결, 협력을 상징합니다. 솔직하고 믿을 만한 파트너를 선택하세요."),
    8: ("风天小畜","風天小畜","Xiao Chu: Taming the Small","Tiểu súc: Thuần hóa nhỏ","소축: 작은 성취",
        "小畜卦象征小有积蓄，但力量尚不足以成就大事。适合做小规模的准备和积累，保持耐心，量变终会引起质变。",
        "小畜卦は小さな蓄積を象徴しますが、まだ大きなことを成す力が足りません。小規模な準備と蓄積に向いています。",
        "Xiao Chu signals small accumulation — not yet enough for major moves. Focus on small-scale preparation and saving.",
        "Quẻ Tiểu súc tượng trưng tích lũy nhỏ, chưa đủ sức làm việc lớn. Phù hợp chuẩn bị quy mô nhỏ.",
        "소축卦는 작은 축적을 상징하지만 아직 큰 일을 할 힘이 부족합니다. 소규모 준비에 적합합니다."),
    9: ("天泽履","天沢履","Lü: Treading","Lǚ: Đi trên vỏ trứng","리: 조심스러운 걸음",
        "履卦象征如履薄冰般的谨慎行事。每一步都要小心谨慎，遵守礼仪和规则，以谦逊的态度对待周围的人。",
        "履卦は薄氷の上を歩くような慎重さを象徴します。一歩一歩慎重に、礼儀とルールを守りましょう。",
        "Lü advises treading carefully, like walking on thin ice. Follow rules, be humble, and you will navigate safely.",
        "Quẻ Lǚ khuyên đi cẩn thận như đi trên băng mỏng. Tuân thủ quy tắc và khiêm nhường.",
        "리卦는 얇은 얼음 위를 걷듯 조심스러운 행동을 조언합니다. 규칙을 따르고 겸손하세요."),
    10: ("地天泰","地天泰","Tai: Peace","Thái: Thái bình","태: 태평",
        "泰卦是大吉之卦，象征天地交泰、万事亨通。当前是你运势最好的时期之一。但泰极否来——在顺境中要居安思危。",
        "泰卦は大吉の卦で、天地が交わり万物が通じる象徴です。今の運勢は最も良い時期の一つ。泰極否来の警告もあります。",
        "Tai is supremely auspicious — heaven and earth in harmony. But beware 'peace breeds stagnation': stay vigilant.",
        "Quẻ Thái là quẻ đại cát, thiên địa giao hòa, vạn sự hanh thông. Cần đề phòng thái cực tật lai.",
        "태卦는 대길의 괘로, 천지가 조화롭고 만사가亨通합니다. 태극피래를 경계하세요."),
    11: ("天地否","天地否","Pi: Standstill","Phệ: Bế tắc","비: 막힘",
        "否卦与泰卦相反，象征天地不交、万物不通。否极泰来是必然的规律。在低谷期要做好自我修炼，等待转机。",
        "否卦は泰卦と逆で、天地が交わらず万物が通じない象徴です。否極泰来は必然の理です。",
        "Pi is the opposite of Tai — standstill, blocked communication. But 'standstill leads to peace' is inevitable.",
        "Quẻ Phệ ngược lại với Thái, tượng trưng sự bế tắc. Phệ cực Thái lai là quy luật tất nhiên.",
        "비卦는 태卦와 반대로, 천지가 교류하지 않고 만사가 막힙니다. 비극태래는 필연적입니다."),
    12: ("天火同人","天火同人","Tong Ren: Fellowship","Đồng nhân: Đồng lòng","동인: 동료",
        "同人卦象征志同道合的人聚在一起。合作的关键在于求同存异——虽然大家目标一致，但方式方法可以不同。",
        "同人卦は志を同じくする人々の集まりを象徴します。協力の鍵は「同きを求め異きを存する」です。",
        "Tong Ren means like-minded people gathering. Seek common ground while respecting differences.",
        "Quẻ Đồng nhân tượng trưng những người cùng chí hướng tụ họp. Cầu đồng tồn dị.",
        "동인卦는 같은 뜻을 가진 사람들이 모이는 것을 상징합니다. 공통점을 찾되 차이점을 존중하세요."),
    13: ("火天大有","火天大有","Da You: Great Possession","Đại hữu: Đại hữu","대유: 큰 소유",
        "大有卦象征丰收和富足。拥有丰富的资源和良好的条件。与人分享你的收获，广结善缘，财富和影响力会持续增长。",
        "大有卦は豊穣と富を象徴します。資源を無駄にせず、収穫を分かち合いましょう。",
        "Da You signals abundance. Use resources wisely, share your gains, and build good relationships.",
        "Quẻ Đại hữu tượng trưng sự phong phú. Sử dụng tài nguyên hợp lý, chia sẻ thành quả.",
        "대유卦는 풍요와 부를 상징합니다. 자원을 낭비하지 말고 나누며 좋은 인연을 맺으세요."),
    14: ("地山谦","地山謙","Qian: Modesty","Khiêm: Khiêm nhường","겸: 겸손",
        "谦卦是六十四卦中最吉利的一卦，象征谦虚和低调。越是在顺利的时候越要保持谦逊。谦虚的人处处受到欢迎和帮助。",
        "謙卦は六十四卦の中で最も吉卦であり、謙虚と低姿勢を象徴します。順調な時こそ謙虚を保ちましょう。",
        "Qian is the most auspicious of all 64 hexagrams — modesty and humility. Stay humble especially when things go well.",
        "Quẻ Khiêm là quẻ cát nhất trong 64 quẻ. Vận hạn rất tốt nhưng越是在 thuận lợi越要 giữ khiêm nhường.",
        "겸卦는 64괘 중 가장 길한 괘로, 겸손과 낮춤을 상징합니다. 운세가 좋을 때일수록 겸손을 지키세요."),
    15: ("雷地豫","雷地豫","Yu: Enthusiasm","Dự: Dự bị","예: 예비",
        "豫卦象征愉悦和准备。当前状态不错，适合做准备和计划。也代表音乐和艺术，适合参加文化活动。",
        "豫卦は喜びと準備の象徴です。楽しい気持ちで計画や準備に向いています。",
        "Yu means joy and preparation. Use this happy energy to plan. Also relates to music and arts.",
        "Quẻ Dự tượng trưng niềm vui và sự chuẩn bị. Tâm trạng vui vẻ, phù hợp lập kế hoạch.",
        "예卦는 기쁨과 준비를 상징합니다. 현재 상태가 좋으니 계획과 준비를 하기에 적합합니다."),
    16: ("泽雷随","沢雷随","Sui: Following","Tùy: Theo","수: 따름",
        "随卦象征顺随和适应。顺应时势，灵活调整策略。不要固执己见，学会观察环境的变化并做出调整。",
        "随卦は順応と適応の象徴です。時勢に従い、柔軟に戦略を調整しましょう。",
        "Sui means following and adapting. Go with the flow, adjust strategies flexibly.",
        "Quẻ Tùy tượng trưng sự thuận theo và thích ứng. Linh hoạt điều chỉnh chiến lược.",
        "수卦는 순응과 적응을 상징합니다. 시세에 따라 유연하게 전략을 조정하세요."),
    17: ("山风蛊","山風蠱","Gu: Work on the Decayed","Cổ: Sửa chữa","고: 썩은 것을 고침",
        "蛊卦象征需要整治和改革。有些事情已经积累了问题，需要你正视和解决。虽然过程辛苦，但之后会有焕然一新的感觉。",
        "蛊卦は改革と修正が必要であることを象徴します。根源に正直に向き合いましょう。",
        "Gu signals something has decayed and needs repair. Face root causes courageously. The process is tough, but renewal follows.",
        "Quẻ Cổ tượng trưng cần sửa chữa. Dũng cảm đối mặt gốc rễ, đừng trốn tránh.",
        "고卦는 개혁과 수정이 필요함을 상징합니다. 근본 원인에 용기 있게 맞서세요."),
    18: ("地泽临","地沢臨","Lin: Approach","Lâm: Tiến đến gần","임: 다가옴",
        "临卦象征临近和到来。你所期待的事物正在接近。也代表领导和治理——如果处于管理位置，现在是展现领导力的好时机。",
        "臨卦は接近と到来を象徴します。待ち望んでいるものが近づいてきています。",
        "Lin means approach — what you await is drawing near. If in management, now is your moment to lead.",
        "Quẻ Lâm tượng trưng sự đến gần. Điều bạn mong đợi đang tiến đến. Đây là lúc thể hiện năng lực lãnh đạo.",
        "임卦는 다가옴을 상징합니다. 기대하던 것이 가까이 오고 있습니다. 리더십을 발휘할 좋은 기회입니다."),
    19: ("风地观","風地観","Guan: Contemplation","Quán: Chiêm nghiệm","관: 관찰",
        "观卦象征观察和反思。停下来仔细观察周围的环境和自身的状况。从更高的角度看问题，你会获得重要的洞见。",
        "観卦は観察と内省の象徴です。高い視点から物事を見るように。",
        "Guan means observation and reflection. Look at things from a higher perspective for important insights.",
        "Quẻ Quán tượng trưng quan sát và chiêm nghiệm. Nhìn từ góc độ cao hơn.",
        "관卦는 관찰과 성찰을 상징합니다. 높은 시각에서 바라보면 중요한 통찰을 얻을 수 있습니다."),
    20: ("火雷噬嗑","火雷噬嗑","Shi He: Biting Through","Sắt hợp: Cắn xuyên","咥합: 깨물어 뚫음",
        "噬嗑卦象征障碍需要被清除。果断处理阻碍或不公正的情况。像咬碎硬物一样突破障碍，既要有力度又要有策略。",
        "噬嗑卦は障害の除去を象徴します。果断に対処する必要があります。",
        "Shi He means biting through obstacles. Deal with barriers decisively — forcefully but also strategically.",
        "Quẻ Sắt hợp tượng trưng loại bỏ trở ngại. Cần xử lý dứt khoát, dùng sức mạnh nhưng cũng có chiến lược.",
        "咥합卦는 장애물을 제거해야 함을 상징합니다. 단호하게 처리하세요."),
    21: ("山火贲","山火賁","Bi: Grace","Bí: Trang sức","비: 꾸밈",
        "贲卦象征装饰和文采。注重外表和形式在某些场合是必要的，但不要过分追求外在的华丽而忽视内在的实质。",
        "賁卦は装飾と文采の象徴です。内実を疎かにしないでください。内容と形式の両方を兼顾しましょう。",
        "Bi relates to grace and decoration. Don't sacrifice substance for style. Balance inner content with outer beauty.",
        "Quẻ Bí tượng trưng trang sức. Đừng bỏ qua thực chất. Cần cân bằng nội dung và hình thức.",
        "비卦는 장식과 문채를 상징합니다. 내실을 소홀히 하지 마세요. 내용과 형식을 모두 갖추세요."),
    22: ("风雷益","風雷益","Yi: Increase","D lợi: Tăng trưởng","익: 이로움",
        "益卦象征增益和进步。这是一个非常吉利的卦象，适合大胆行动、推进计划。付出和回报都会增长。",
        "益卦は増益と進歩の象徴です。非常に吉卦であり、大胆に行動し、計画を進めるのに適しています。",
        "Yi means increase — a very auspicious hexagram. Act boldly, push plans forward. Both giving and receiving grow.",
        "Quẻ D lợi tượng trưng tăng trưởng. Rất cát, phù hợp hành động táo bạo. Cả cho và nhận đều tăng.",
        "익卦는 증益과 진보를 상징합니다. 매우 길한 괘로 대담하게 행동하고 계획을 추진하기에 적합합니다."),
    23: ("山地剥","山地剥","Bo: Splitting Apart","Bác: Phá vỡ","박: 무너짐",
        "剥卦象征剥落和衰退。不宜做大的行动或决定，应该韬光养晦、保存实力。等到底部稳了自然会重新生长。",
        "剥卦は剥離と衰退の象徴です。大きな行動や決定を控え、力を蓄えるべきです。",
        "Bo signals decline. Don't make big moves now — conserve your strength. Once the base stabilises, growth returns.",
        "Quẻ Bác tượng trưng sự suy tàn. Đừng hành động lớn, nên ẩn dật chờ thời.",
        "박卦는 파열과 쇠퇴을 상징합니다. 큰 행동을 자제하고 힘을 비축하세요."),
    24: ("地雷复","地雷復","Fu: Return","Phục: Phục hồi","복: 돌아옴",
        "复卦象征回归和重生。在经历了低谷之后，你即将迎来新的开始。抓住这个转机，积极行动起来。",
        "復卦は回帰と再生を象徴します。低谷を経て、新たな始まりが近づいています。この転機を捉えましょう。",
        "Fu signals return and rebirth. After hardship, new beginnings approach. Grasp this opportunity.",
        "Quẻ Phục tượng trưng phục hồi và tái sinh. Sau khó khăn, khởi đầu mới đang đến.",
        "복卦는 돌아옴과 재탄생을 상징합니다. 고난 후에 새로운 시작이 옵니다."),
    25: ("天雷无妄","天雷無妄","Wu Wang: Innocence","Vô v妄: Vô tội","무망: 순진",
        "无妄卦象征纯真和自然。不要刻意做作，保持真诚和自然的态度反而会获得好的结果。意外事件可能是考验。",
        "無妄卦は純粋さと自然さの象徴です。意図的に何かをするのではなく、正直で自然な姿勢が良い結果をもたらします。",
        "Wu Wang means innocence and naturalness. Stay sincere and natural — forced actions backfire. Unexpected events may test you.",
        "Quẻ Vô v妄 tượng trưng sự thuần khiết và tự nhiên. Giữ chân thành, hành động cưỡng ép sẽ phản tác dụng.",
        "무망卦는 순수함과 자연스러움을 상징합니다. 인위적으로 하지 말고 정직하고 자연스러운 태도가 좋은 결과를 가져옵니다."),
    26: ("山天大畜","山天大畜","Da Chu: Taming the Great","Đại súc: Thuần hóa lớn","대축: 큰 성취",
        "大畜卦象征大的积蓄和停止。当前适合大量积累知识、财富和经验。不急于行动，厚积薄发方为上策。",
        "大畜卦は大きな蓄積と停止の象徴です。知識・富・経験を大量に蓄える時期。急がず、厚く積んで薄く発すのが最善です。",
        "Da Chu signals great accumulation. Now is the time to gather knowledge, wealth, and experience. Don't rush — build deep reserves.",
        "Quẻ Đại súc tượng trưng tích lũy lớn. Đây là lúc thu thập kiến thức, tiền bạc và kinh nghiệm. Đừng vội, tích lũy sâu.",
        "대축卦는 큰 축적과 멈춤을 상징합니다. 지식, 부, 경험을 대량으로 비축하는 시기입니다."),
    27: ("山雷颐","山雷頤","Yi: Nourishment","Dưỡng: Nuôi dưỡng","이: 먹이미",
        "颐卦象征滋养和养育。注意你吃什么、说什么、接触什么。近朱者赤，近墨者黑——你的环境和习惯塑造了你。",
        "頤卦は栄養と養育の象徴です。何を食べ、何を言い、何に触れるかに注意。環境と習慣が自分を作ります。",
        "Yi means nourishment. Watch what you eat, say, and expose yourself to. Your environment and habits shape you.",
        "Quẻ Dưỡng tượng trưng nuôi dưỡng. Chú ý ăn gì, nói gì, tiếp xúc gì. Môi trường và thói quen định hình bạn.",
        "이卦는 먹이미와 양육을 상징합니다. 무엇을 먹고, 말하고, 접하는지에 주의하세요."),
    28: ("泽风大过","沢風大過","Da Guo: Preponderance of the Great","Đại quá: Quá mức","대과: 지나침",
        "大过卦象征事情发展到了极端。压力很大，需要非常规的手段来解决问题。但物极必反，极端之后会有转机。",
        "大過卦は物事が極端に達した象徴です。プレッシャーが大きく、非常な手段が必要です。物極必反、転機があります。",
        "Da Guo signals extreme pressure — extraordinary measures needed. But extremes reverse; a turning point will come.",
        "Quẻ Đại quá tượng trưng sự cực đoan. Áp lực lớn, cần biện pháp đặc biệt. Nhưng cực điểm sẽ xoay chuyển.",
        "대과卦는 사물이 극한에 도달했음을 상징합니다. 압박이 크지만 전환점이 올 것입니다."),
    29: ("坎为水","坎為水","Kan: The Abysmal","Khảm: Nguy hiểm","감: 위험",
        "坎卦象征险难和陷阱。当前你可能面临困难和危险，但坎卦也教导我们在险境中保持诚信和勇气，终能渡过难关。",
        "坎卦は危険と罠の象徴です。困難に直面していますが、誠実さと勇気を保てば必ず乗り越えられます。",
        "Kan represents danger and pitfalls. You may face difficulties, but maintaining integrity and courage will see you through.",
        "Quẻ Khảm tượng trưng hiểm nguy. Có thể đối mặt khó khăn, nhưng giữ trung thực và dũng cảm sẽ vượt qua.",
        "감卦는 위험과 함정을 상징합니다. 어려움에 직면할 수 있지만, 성실함과 용기를 유지하면 반드시 극복할 수 있습니다."),
    30: ("离为火","離為火","Li: The Clinging","Ly: Dính liền","리: 따름",
        "离卦象征附着和光明。火需要依附在物体上才能燃烧，人也需要依托才能发展。找到正确的依托，发挥自己的光和热。",
        "離卦は付着と光明の象徴。火は物に依存して燃え、人も依托があって発展できます。正しい依托を見つけましょう。",
        "Li means clinging and brightness. Fire needs fuel to burn; people need foundations to thrive. Find the right foundation.",
        "Quẻ Ly tượng trưng sự bám víu và ánh sáng. Lửa cần nhiên liệu, người cần nền tảng. Tìm nền tảng đúng.",
        "리卦는 의지와 빛을 상징합니다. 불은 연료가 있어야 타고, 사람은 토대가 있어야 발전합니다."),
    31: ("泽山咸","沢山咸","Xian: Influence","Cảm: Ảnh hưởng","함: 감응",
        "咸卦象征感应和相互影响。感情上容易产生共鸣，适合表达爱意。也暗示人际关系中默契和直觉的重要性。",
        "咸卦は感応と相互影響の象徴です。感情の共鳴が生まれやすい時期。愛情を伝えるのに適しています。",
        "Xian means influence and mutual resonance. Emotional connections form easily — good time to express love.",
        "Quẻ Cảm tượng trưng cảm ứng và ảnh hưởng lẫn nhau. Dễ tạo sự đồng cảm, phù hợp bày tỏ tình cảm.",
        "함卦는 감응과 상호 영향을 상징합니다. 감정적 공감이 생기기 쉬운 시기. 사랑을 표현하기 좋습니다."),
    32: ("雷风恒","雷風恒","Heng: Duration","Hằng: Lâu dài","항: 영구",
        "恒卦象征持久和恒心。做事要有恒心和毅力，不要三天打鱼两天晒网。坚持正确的方向，终会看到成果。",
        "恒卦は持続と粘り強さの象徴です。正しい方向を持ち、粘り強く続けましょう。",
        "Heng means duration and perseverance. Stay the course with persistence. Consistent effort over time yields results.",
        "Quẻ Hằng tượng trưng sự bền bỉ. Kiên trì theo hướng đúng, nỗ lực liên tục sẽ có kết quả.",
        "항卦는 지속과 끈기를 상징합니다. 올바른 방향을 가지고 꾸준히 노력하면 결과가 있을 것입니다."),
    33: ("天山遁","天山遯","Dun: Retreat","Đốn: Rút lui","둔: 물러남",
        "遁卦象征退避和隐退。当前不宜硬碰硬，适当的战略性撤退不是懦弱而是智慧。保存实力，等待更好的时机。",
        "遯卦は退避と隠退の象徴です。戦略的な撤退は懦弱ではなく知恵です。力を蓄えて良い时机を待ちましょう。",
        "Dun signals strategic retreat. Pulling back isn't weakness — it's wisdom. Conserve strength for better times.",
        "Quẻ Đốn tượng trưng rút lui. Rút chiến lược không phải yếu đuối — đó là trí tuệ. Tích lũy chờ thời.",
        "둔卦는 퇴피와 은퇴를 상징합니다. 전략적 후퇴는 나약함이 아니라 지혜입니다."),
    34: ("雷天大壮","雷天大壮","Da Zhuang: Great Power","Đại tráng: Lực mạnh","대장: 큰 힘",
        "大壮卦象征力量强大。你正处于能量充沛的阶段，但壮而不过——力量要用在正确的地方，不可恃强凌弱。",
        "大壮卦は力強さの象徴です。エネルギーに満ちていますが、力は正しい場所で使いましょう。",
        "Da Zhuang means great power. You have abundant energy, but use it correctly — don't abuse strength.",
        "Quẻ Đại tráng tượng trưng lực lượng mạnh. Năng lượng dồi dào, nhưng dùng đúng chỗ — đừng lạm dụng sức mạnh.",
        "대장卦는 큰 힘을 상징합니다. 에너지가 넘치지만 올바른 곳에서 사용하세요."),
    35: ("火地晋","火地晋","Jin: Progress","Tấn: Tiến bộ","진: 발전",
        "晋卦象征进步和上升。像太阳从地面升起一样，你的事业和人生正在上升期。抓住机会，积极进取。",
        "晋卦は進歩と上昇の象徴です。太陽が地平線から昇るように、あなたの人生は上昇期にあります。",
        "Jin means progress and advancement. Like the sun rising, your career and life are ascending. Seize opportunities.",
        "Quẻ Tấn tượng trưng sự tiến bộ. Như mặt trời mọc, sự nghiệp và cuộc sống đang lên. Nắm bắt cơ hội.",
        "진卦는 진보와 상승을 상징합니다. 태양이 지평선에서 떠오르듯 당신의 인생은 상승기에 있습니다."),
    36: ("地火明夷","地火明夷","Ming Yi: Darkening of the Light","Minh di: Ánh sáng mờ","명이: 빛이 어두워짐",
        "明夷卦象征光明受损。当前可能遭遇不公正的对待或才能被埋没。韬光养晦，暗中积蓄力量，等待重见光明的那一天。",
        "明夷卦は光が損なわれる象徴です。不正な扱いを受けるかもしれませんが、力を蓄えて光が戻るのを待ちましょう。",
        "Ming Yi means darkened light. You may face injustice or be overlooked. Hide your brilliance and wait for dawn.",
        "Quẻ Minh di tượng trưng ánh sáng bị tổn hại. Có thể gặp bất công, hãy ẩn dật chờ bình minh.",
        "명이卦는 빛이 손상됨을 상징합니다. 불공정한 대우를 받을 수 있지만 힘을 비축하고 새벽을 기다리세요."),
    37: ("风火家人","風火家人","Jia Ren: The Family","Gia nhân: Gia đình","가인: 가정",
        "家人卦象征家庭和内务。重视家庭关系，营造和谐的家庭氛围。家和万事兴——家庭和睦是一切顺利的基础。",
        "家人卦は家庭と内務の象徴です。家庭関係を大切にし、調和のとれた雰囲気を作りましょう。",
        "Jia Ren represents family and household. Cherish family relationships and create harmony. A peaceful home is the foundation.",
        "Quẻ Gia nhân tượng trưng gia đình. Trân trọng quan hệ gia đình, tạo bầu không khí hòa hợp.",
        "가인卦는 가정과 가내를 상징합니다. 가족 관계를 소중히 하고 조화로운 분위기를 만드세요."),
    38: ("火泽睽","火沢睽","Kui: Opposition","Khué: Phản đối","괴: 반목",
        "睽卦象征对立和分歧。当前可能与他人意见不合或立场对立。但睽卦也暗示对立中蕴含着合作的可能——求同存异。",
        "睽卦は対立と分岐の象徴です。他人と意見が合わないかもしれませんが、対立の中に協力の可能性も潜んでいます。",
        "Kui means opposition. You may disagree with others, but opposition contains the seeds of cooperation — find common ground.",
        "Quẻ Khué tượng trưng sự đối lập. Có thể bất đồng với người khác, nhưng trong đối lập ẩn chứa khả năng hợp tác.",
        "괴卦는 대립과 분기를 상징합니다. 타인과 의견이 다를 수 있지만 대립 속에 협력의 가능성이 있습니다."),
    39: ("水山蹇","水山蹇","Jian: Obstruction","Giản: Trở ngại","건: 곤란",
        "蹇卦象征困难和阻碍。前进的道路上有障碍，不宜冒进。反省自身不足，寻求帮助，迂回前进往往比硬冲更有效。",
        "蹇卦は困難と障害の象徴です。急進せず、自身の不足を反省し、助けを求めましょう。",
        "Jian signals obstacles ahead. Don't rush forward. Reflect, seek help, and take a detour — it's often more effective.",
        "Quẻ Giản tượng trưng trở ngại. Đừng vội tiến lên. Suy ngẫm, nhờ giúp đỡ, đi đường vòng thường hiệu quả hơn.",
        "건卦는 어려움과 장애를 상징합니다. 무리하게 나아가지 말고 스스로를 성찰하고 도움을 구하세요."),
    40: ("雷水解","雷水解","Xie: Deliverance","Giải: Giải thoát","해: 풀림",
        "解卦象征困难解除、问题解决。之前的阻碍正在消散，是采取行动解决问题的好时机。抓紧时间处理积压的事务。",
        "解卦は困難の解除と問題解決の象徴です。以前の障害が消え、行動を起こす好機です。",
        "Xie means deliverance — problems dissolving. Old obstacles fade. Act now to resolve pending matters.",
        "Quẻ Giải tượng trưng sự giải thoát. Trở ngại cũ đang tan biến. Hãy hành động giải quyết vấn đề.",
        "해卦는 어려움 해소와 문제 해결을 상징합니다. 이전의 장애가 사라지고 행동할 좋은 기회입니다."),
    41: ("山泽损","山沢損","Sun: Decrease","Tổn: Giảm损","손: 손실",
        "损卦象征减损和付出。当前需要有所牺牲或付出才能获得更大的回报。先损后益——短期的付出会带来长期的收获。",
        "損卦は減損と犠牲の象徴です。大きな見返りを得るために今は犠牲を払う時期。先に損して後に益する。",
        "Sun means decrease — sacrifice now for greater gain later. Short-term loss leads to long-term gain.",
        "Quẻ Tổn tượng trưng giảm損. Hy sinh bây giờ để nhận lại lớn hơn. Mất ngắn hạn, lợi dài hạn.",
        "손卦는 감소와 희생을 상징합니다. 큰 대가를 얻기 위해 지금은 희생이 필요한 시기입니다."),
    42: ("风雷益","風雷益","Yi: Increase","D lợi: Tăng trưởng","익: 이로움",
        "益卦象征增益和进步。这是一个非常吉利的卦象，适合大胆行动、推进计划。付出和回报都会增长。",
        "益卦は増益と進歩の象徴です。非常に吉卦であり、大胆に行動し、計画を進めるのに適しています。",
        "Yi means increase — a very auspicious hexagram. Act boldly, push plans forward. Both giving and receiving grow.",
        "Quẻ D lợi tượng trưng tăng trưởng. Rất cát, phù hợp hành động táo bạo. Cả cho và nhận đều tăng.",
        "익卦는 증益과 진보를 상징합니다. 매우 길한 괘로 대담하게 행동하고 계획을 추진하기에 적합합니다."),
    43: ("泽天夬","沢天夬","Guai: Breakthrough","Quải: Phá vỡ","괴: 결단",
        "夬卦象征果断突破。积压已久的问题需要一个痛快的解决。果断行动，但要注意方式方法——刚中有柔，不要伤及无辜。",
        "夬卦は果断な突破の象徴です。長く積み上がった問題を解決する時。果断に行動しましょう。",
        "Guai means breakthrough. Long-standing issues need decisive resolution. Act firmly but with tact.",
        "Quẻ Quải tượng trưng phá vỡ quyết đoán. Vấn đề tích lũy cần xử lý dứt khoát. Hành động kiên quyết nhưng khéo léo.",
        "괴卦는 단호한 돌파를 상징합니다. 오래 쌓인 문제를 해결할 때입니다. 단호하게行动하되 적절한 방법을 쓰세요."),
    44: ("天风姤","天風姤","Gou: Coming to Meet","Cấu: Gặp gỡ","구: 만남",
        "姤卦象征不期而遇。可能遇到意想不到的人或事。要保持警惕——有些相遇看似美好实则有隐患。分辨善缘和孽缘。",
        "姤卦は予期せぬ出会いの象徴です。警戒を怠らず、善縁と悪縁を見分けましょう。",
        "Gou means unexpected encounter. Be vigilant — some meetings seem good but hide risks. Distinguish blessing from trouble.",
        "Quẻ Cấu tượng trưng sự gặp gỡ bất ngờ. Cảnh giác — một số cuộc gặp tưởng tốt nhưng ẩn chứa rủi ro.",
        "구卦는 예상치 못한 만남을 상징합니다. 경계를 게을리하지 말고 선연과 악연을 구별하세요."),
    45: ("泽地萃","沢地萃","Cui: Gathering Together","Túi: Tập hợp","취: 모임",
        "萃卦象征聚集和团结。适合参加集体活动、团队合作。在人群中你能找到志同道合的伙伴，也能获得他人的帮助。",
        "萃卦は聚集と団結の象徴です。集体活動やチームワークに向いています。人群中で志を同じくする仲間が見つかります。",
        "Cui means gathering together. Participate in group activities and teamwork. You'll find like-minded companions and receive help.",
        "Quẻ Túi tượng trưng tập hợp. Tham gia hoạt động nhóm, hợp tác tập thể. Tìm được đồng chí hướng và nhận giúp đỡ.",
        "취卦는 모임과 단결을 상징합니다. 그룹 활동과 팀워크에 적합합니다. 뜻이相同的인 동료를 찾을 수 있습니다."),
    46: ("地风升","地風升","Sheng: Pushing Upward","Thăng: Thăng tiến","승: 상승",
        "升卦象征上升和进步。像树木从地面生长一样，你的能力和地位正在稳步上升。继续保持努力，前途一片光明。",
        "升卦は上昇と進歩の象徴です。木が地面から育つように、あなたの能力と地位は着実に上昇しています。",
        "Sheng means pushing upward. Like a tree growing from the ground, your abilities and status are steadily rising.",
        "Quẻ Thăng tượng trưng sự thăng tiến. Như cây mọc từ đất, năng lực và địa vị đang lên đều đặn.",
        "승卦는 상승과 진보를 상징합니다. 땅에서 자라나는 나무처럼 당신의 능력과 지위가 안정적으로 상승하고 있습니다."),
    47: ("泽水困","沢水困","Kun: Oppression","Khốn: Nghèo khó","곤: 곤궁",
        "困卦象征困顿和穷途。当前可能感到处处受限、施展不开。但困卦也暗示——困极则通，最困难的时候往往就是转机将至的时候。",
        "困卦は困難と窮地の象徴です。制限を感じるかもしれませんが、困極則通——最も難しい時こそ転機が近づいています。",
        "Kun means oppression. You may feel trapped, but extreme hardship signals that relief is near.",
        "Quẻ Khốn tượng trưng nghèo khó. Cảm thấy bị hạn chế, nhưng cực khổ cùng cực báo hiệu sự nhẹ nhõm đang đến.",
        "곤卦는 곤핍과 궁지를 상징합니다. 제한을 느낄 수 있지만, 가장 힘든 때가 전환점이 가까운 때입니다."),
    48: ("水风井","水風井","Jing: The Well","Tĩnh: Giếng nước","정: 우물",
        "井卦象征源泉和供给。像井水取之不尽一样，你需要找到自己源源不断的能量来源。也要注意——井需要维护，否则水会变浑。",
        "井卦は源泉と供給の象徴です。井戸の水のように切れないエネルギーの源を見つけましょう。井戸はメンテナンスも必要です。",
        "Jing means the well — an inexhaustible source. Find your continuous energy supply. But wells need maintenance too.",
        "Quẻ Tĩnh tượng trưng nguồn suối. Tìm nguồn năng lượng không cạn kiệt. Nhưng giếng cũng cần bảo trì.",
        "정卦는 원천과 공급을 상징합니다. 끊이지 않는 에너지원을 찾으세요. 우물도 관리가 필요합니다."),
    49: ("泽火革","沢火革","Ge: Revolution","Cách: Cách mạng","혁: 변혁",
        "革卦象征变革和革新。旧的模式已经不再适用，需要彻底改变。变革虽然痛苦，但之后会迎来全新的局面。把握时机，果断行动。",
        "革卦は変革と革新の象徴です。古いパターンはもう適用できず、根本的な変化が必要です。",
        "Ge means revolution — old patterns no longer work. Fundamental change is needed. Though painful, it brings a fresh start.",
        "Quẻ Cách tượng trưng cách mạng. Mô hình cũ không còn phù hợp, cần thay đổi căn bản.",
        "혁卦는 변혁과 혁신을 상징합니다. 오래된 패턴이 더 이상 맞지 않아 근본적인 변화가 필요합니다."),
    50: ("火风鼎","火風鼎","Ding: The Cauldron","Đỉnh: đỉnh","정: 솥",
        "鼎卦象征烹饪和转化。把原始的食材转化为美味的佳肴——你正在经历一个转化和提升的过程。把握这个蜕变的机会。",
        "鼎卦は調理と変容の象徴です。原料を美味に変えるように、変容と成長の過程にあります。",
        "Ding represents transformation — turning raw ingredients into something refined. You're in a phase of growth and metamorphosis.",
        "Quẻ Đỉnh tượng trưng sự chuyển hóa. Biến nguyên liệu thô thành tinh túy. Bạn đang trong giai đoạn phát triển.",
        "정卦는 요리와 전환을 상징합니다. 원래 재료를 맛있는 요리로 바꾸듯 변환과 성장의 과정에 있습니다."),
    51: ("震为雷","震為雷","Zhen: Thunder","Chấn: Sấm sét","진: 번개",
        "震卦象征震动和惊醒。突如其来的变化或事件让你震惊，但这也是一次唤醒。从惊恐中清醒过来，你会更加清醒和坚定。",
        "震卦は震動と覚醒の象徴です。予期せぬ変化に驚くかもしれませんが、それは目覚めでもあります。",
        "Zhen represents thunder — sudden shock that awakens. Unexpected events may startle you, but they also bring clarity.",
        "Quẻ Chấn tượng trưng sấm sét — chấn động đột ngột làm thức tỉnh. Sự kiện bất ngờ gây shock nhưng cũng mang lại sự sáng suốt.",
        "진卦는 진동과 각성을 상징합니다. 예상치 못한 변화에 놀랄 수 있지만, 그것은 각성이기도 합니다."),
    52: ("艮为山","艮為山","Gen: Keeping Still","Cấn: Yên tĩnh","간: 그침",
        "艮卦象征停止和静止。当前最重要的是停下来，让内心归于平静。冥想、独处、反省——在静止中找到答案。",
        "艮卦は停止と静寂の象徴です。今は最重要なのは立ち止まり、心を落ち着けることです。瞑想・独省・反省で答えを見つけましょう。",
        "Gen means keeping still. The most important thing now is to stop and find inner peace. Meditate, reflect, find answers in stillness.",
        "Quẻ Cấn tượng trưng sự dừng lại và tĩnh lặng. Điều quan trọng nhất bây giờ là dừng lại và tìm sự bình yên nội tâm.",
        "간卦는 멈춤과 고요를 상징합니다. 지금 가장 중요한 것은 멈추고 내면의 평화를 찾는 것입니다."),
    53: ("风山渐","風山漸","Jian: Gradual Progress","Tiến: Dần dần","점: 점진",
        "渐卦象征循序渐进。事物在按照正确的节奏缓慢发展。不要急于求成，按部就班地推进，水到渠成。",
        "漸卦は段階的な進歩の象徴です。物事は正しいリズムでゆっくり発展しています。急がず、段階的に進めましょう。",
        "Jian means gradual progress. Things develop at the right pace. Don't rush — step by step, success comes naturally.",
        "Quẻ Tiến tượng trưng tiến triển dần dần. Sự việc phát triển theo nhịp đúng. Đừng vội, từng bước sẽ thành công.",
        "점卦는 점진적 진보를 상징합니다. 사물이 올바른 리듬으로 천천히 발전하고 있습니다. 서두르지 마세요."),
    54: ("雷泽归妹","雷沢帰妹","Gui Mei: The Marrying Maiden","Quy muội: Cô gái lấy chồng","귀매: 시집가는 아가씨",
        "归妹卦象征婚嫁和新的开始。可能有一段新的关系或合作开始，但要认清现实——不是所有的开始都有完美的结局。",
        "帰妹卦は婚嫁と新たな始まりの象徴です。新しい関係や協力が始まるかもしれませんが、現実を見極めましょう。",
        "Gui Mei represents new beginnings — a new relationship or partnership may form, but see reality clearly.",
        "Quẻ Quy muội tượng trưng khởi đầu mới — mối quan hệ hoặc hợp tác mới có thể bắt đầu, nhưng hãy nhìn thẳng vào thực tế.",
        "귀매卦는 혼인과 새로운 시작을 상징합니다. 새로운 관계나 협력이 시작될 수 있지만 현실을 명확히 보세요."),
    55: ("雷火丰","雷火豐","Feng: Abundance","Phong: Sung túc","풍: 풍요",
        "丰卦象征丰盛和繁荣。当前是你最辉煌的时期之一。但盛极必衰——在最丰盛的时候要居安思危，为将来做准备。",
        "豐卦は豊かさと繁栄の象徴です。最も輝かしい時期の一つ。盛者必衰——繁栄の時にこそ未来の準備を。",
        "Feng means abundance — one of your most brilliant periods. But peaks decline; prepare for the future during prosperity.",
        "Quẻ Phong tượng trưng sung túc. Giai đoạn rực rỡ nhất. Nhưng thịnh必 suy — hãy chuẩn bị cho tương lai.",
        "풍卦는 풍요와 번영을 상징합니다. 가장 빛나는 시기 중 하나입니다. 그러나 성하면 쇠퇴하니 미래를 준비하세요."),
    56: ("火山旅","火山旅","Lü: The Wanderer","Lữ: Khách lãng du","려: 나그네",
        "旅卦象征旅行和漂泊。身处异乡或陌生环境，需要谨慎和适应。保持谦逊低调，尊重当地的规矩和文化。",
        "旅卦は旅行と放浪の象徴です。異郷や慣れない環境では慎重さと適応力が求められます。",
        "Lü represents the wanderer — in unfamiliar territory. Stay humble, observe local customs, and adapt carefully.",
        "Quẻ Lữ tượng trưng người lữ hành.ở vùng đất lạ, cần khiêm nhường và thích ứng cẩn thận.",
        "려卦는 여행과 나그네를 상징합니다. 낯선 곳에서는 겸손하고 현지 관습을 존중하며 적응하세요."),
    57: ("巽为风","巽為風","Xun: The Gentle","Tốn: Hiền hòa"," 솔: 바람",
        "巽卦象征渗透和柔和。像风一样无孔不入，用柔和的方式影响周围的人。不要硬碰硬，以柔克刚才是上策。",
        "巽卦は浸透と柔らかさの象徴です。風のように隙間なく、柔らかい方法で周囲に影響を与えましょう。",
        "Xun means gentle penetration — like wind, influence others softly. Soft approaches overcome hard resistance.",
        "Quẻ Tốn tượng trưng sự thấm nhuần và hiền hòa. Như gió, ảnh hưởng người khác bằng sự mềm mại.",
        "솔卦는 침투와 유연함을 상징합니다. 바람처럼 모든 틈새로 스며들어 부드러운 방식으로 영향을 미치세요."),
    58: ("兑为泽","兑為澤","Dui: The Joyous","Đoài: Vui vẻ","태: 기쁨",
        "兑卦象征喜悦和交流。人际关系和谐融洽，适合社交和表达。你的乐观和开朗会感染周围的人。",
        "兑卦は喜びと交流の象徴です。人間関係が調和し、社交や表現に向いています。",
        "Dui means joy and communication. Relationships are harmonious — great for socialising and expressing yourself.",
        "Quẻ Đoài tượng trưng niềm vui và giao tiếp. Quan hệ hài hòa, phù hợp giao lưu và bày tỏ.",
        "태卦는 기쁨과 소통을 상징합니다. 인간관계가 조화롭고 사교와 표현에 적합합니다."),
    59: ("风水涣","風水渙","Huan: Dispersion","Huan: Phân tán","환: 흩어짐",
        "涣卦象征涣散和化解。当前可能感到人心涣散或精力分散。涣卦建议通过精神力量（信仰、文化、共同目标）来重新凝聚人心。",
        "渙卦は涣散と化解の象徴です。人心が離れたりエネルギーが分散したりしているかもしれません。精神的な力で再凝集しましょう。",
        "Huan means dispersion. People may feel scattered. Reunite through spiritual strength — shared beliefs, culture, common goals.",
        "Quẻ Huan tượng trưng sự phân tán. Mọi người có thể cảm thấy phân tâm. Tái凝聚 bằng sức mạnh tinh thần.",
        "환卦는 흩어짐과 해소를 상징합니다. 사람들이 흩어지거나 에너지가 분산될 수 있습니다. 정신력으로 다시 결집하세요."),
    60: ("水泽节","水沢節","Jie: Limitation","Tiết: Tiết chế","절: 절제",
        "节卦象征节制和限度。凡事要有度——过度放纵或过度节俭都不好。找到合适的平衡点，有节制地生活和工作。",
        "節卦は節制と限度の象徴です。何事にも度があります——過度の放縦も過度の節約も良くない。バランスを見つけましょう。",
        "Jie means limitation and moderation. Everything has its limit — find the right balance in work and life.",
        "Quẻ Tiết tượng trưng tiết chế. Mọi thứ đều có giới hạn — tìm sự cân bằng phù hợp.",
        "절卦는 절제와 한도를 상징합니다. 모든 것에는 정도가 있습니다 — 적절한 균형을 찾으세요."),
    61: ("风泽中孚","風沢中孚","Zhong Fu: Inner Truth","Trung thự: Lòng trung thực","중孚: 진실된 마음",
        "中孚卦象征内心的真诚和信任。以真心待人，自然会获得他人的信任。信任是人际关系中最宝贵的资产。",
        "中孚卦は内なる真実と信頼の象徴です。真心で人に対すれば、自然と信頼を得られます。",
        "Zhong Fu means inner truth and trust. Treat others with genuine sincerity and trust follows naturally.",
        "Quẻ Trung thự tượng trưng sự chân thật nội tâm. Đối xử chân thành với người khác, lòng tin sẽ đến tự nhiên.",
        "중孚卦는 내면의 진실과 신뢰를 상징합니다. 진심으로 대하면 자연스럽게 신뢰를 얻게 됩니다."),
    62: ("雷山小过","雷山小過","Xiao Guo: Preponderance of the Small","Tiểu quá: Quá nhỏ","소과: 작은 지나침",
        "小过卦象征小事上的过度。做小事可以大胆一些，但做大事要格外谨慎。小事不拘，大事不苟。",
        "小過卦は小事の過度の象徴です。小さなことでは大胆に、大きなことでは特に慎重に。",
        "Xiao Guo means excess in small things. Be bold with small matters, but extra careful with big decisions.",
        "Quẻ Tiểu quá tượng trưng sự quá mức trong việc nhỏ. Táo bạo với việc nhỏ, cẩn thận với việc lớn.",
        "소과卦는 작은 일에서의 지나침을 상징합니다. 작은 일은 대담하게, 큰 일은 특별히 조심하세요."),
    63: ("水火既济","水火既済","Ji Ji: After Completion","Kỷ tế: Hoàn thành","기제: 이루어짐",
        "既济卦象征完成和圆满。事情已经成功完成，但既济之后便是未济——完成不是终点，要为下一个阶段做准备。居安思危。",
        "既済卦は完成と円満の象徴です。物事が成功裏に完成しましたが、既済の後は未済——完成は終点ではありません。",
        "Ji Ji means completion. Things are done successfully, but after completion comes a new challenge. Prepare for what's next.",
        "Quẻ Kỷ tế tượng trưng sự hoàn thành. Mọi thứ đã thành công, nhưng sau hoàn thành là thử thách mới.",
        "기제卦는 완성과 원만함을 상징합니다. 일이 성공적으로 끝났지만, 완성 후에는 새로운 도전이 옵니다."),
}

# ===== Per-fortune data for hexagrams 23-63 (zh + en) =====
# ja/vi/ko are derived from the overall desc translations in _HEX_DATA

_FORTUNE_ZH = {
    23: ("感情上可能经历一段低潮或冷淡期。有伴侣者需要更多耐心，不要在情绪低落时做重要决定。单身者暂时不宜主动追求，先调整好自己的状态。",
         "事业上可能遇到瓶颈或资源不足的情况。不宜做大变动，稳守当前岗位，积累实力等待时机。",
         "财运偏弱，不宜投资或大额消费。做好储蓄，控制支出，等待财运回升。",
         "身体容易疲劳，免疫力下降。注意休息，避免过度劳累，定期体检。",
         "人际关系可能有些疏远，不适合社交应酬。独处反思，修复内心能量。"),
    24: ("感情上迎来新的转机。之前冷淡的关系可能回暖，单身者有望遇到新的桃花。把握机会，主动但不急躁。",
         "事业上之前停滞的项目可能重新启动。把握复苏的机会，积极行动但要稳扎稳打。",
         "财运开始回升，可能有意外的小收入。适合开始小额储蓄和理财计划。",
         "健康状况从低谷回升，精力逐渐恢复。适合开始规律运动，重建健康习惯。",
         "人际关系回暖，与疏远的朋友重新联系。适合参加社交活动，拓展人脉。"),
    25: ("感情上容易遇到意外的人或事。保持真诚自然的态度，不要刻意做作。顺其自然反而会有好的缘分。",
         "事业上可能遇到意外的变动或机遇。保持冷静，不要被突发事件打乱节奏。",
         "财运有意外的波动，可能有意外支出也可能有意外收入。保持理性消费。",
         "身体可能出现突发的小状况，但不严重。注意饮食卫生和作息规律。",
         "出行可能遇到小波折，但总体平安。保持平常心，灵活应对变化。"),
    26: ("感情上适合慢慢培养，不宜急于求成。花时间深入了解对方，建立扎实的感情基础。",
         "事业上处于积累期，不适合跳槽或创业。深耕当前领域，提升专业技能。",
         "财运适合长期投资和储蓄。不适合短线操作，坚持定投策略。",
         "身体需要好好调养，适合做全面体检。注意肠胃保养，饮食规律。",
         "人际关系上适合与志同道合的人深度交流。少一些无效社交，多一些有质量的对话。"),
    27: ("感情上要注意言行一致。不要说一套做一套，真诚是最好的恋爱策略。",
         "事业上要选择正确的学习方向。跟对导师、选对行业比努力更重要。",
         "财运要选择正确的理财方式。学习基础的金融知识，避免被骗。",
         "身体需要注意饮食健康。病从口入，注意食品安全和营养均衡。",
         "人际交往要选择良师益友。远离负能量的人，多与积极向上的人交往。"),
    28: ("感情上可能承受较大压力。关系中可能出现一些非常规的状况，需要你有勇气面对和处理。",
         "事业上面临重大挑战，可能需要非常规的手段来解决问题。鼓起勇气突破困境。",
         "财务上可能面临较大压力或风险。谨慎决策，不要孤注一掷。",
         "身体可能有较大的透支信号。必须重视健康，必要时及时就医。",
         "人际关系中可能遇到棘手的问题。保持冷静理性，寻求专业帮助。"),
    29: ("感情上可能经历险境或考验。不要在困难时期做重大感情决定。保持诚信和勇气，困难终会过去。",
         "事业上面临风险和挑战。谨慎行事，不要冒险。遇到困难时寻求帮助。",
         "财务上可能有风险或损失。保守理财，不要参与高风险投资。",
         "身体可能有较大的隐患。定期体检，有问题及时处理，不要拖延。",
         "出行注意安全，避免冒险活动。人际交往中提防小人，保持警惕。"),
    30: ("感情上需要找到正确的依托。选择一个能让你发光发热的伴侣，互相成就。",
         "事业上要找到正确的平台和方向。依托好的团队和领导，发挥自己的光和热。",
         "财运需要正确的理财依托。选择可靠的理财渠道，不要盲目跟风。",
         "身体需要正确的生活方式依托。建立健康的作息和饮食习惯。",
         "人际关系中要找到真正值得交往的朋友。真诚相待，建立稳固的友谊。"),
    31: ("感情上容易产生共鸣和吸引。适合表白或确认关系。直觉和默契在这段时间特别强烈。",
         "事业上容易得到他人的支持和帮助。人际关系和谐，适合团队合作。",
         "财运有人脉带来的机会。通过社交和合作可能获得不错的收入。",
         "身体状态不错，心情愉悦对健康很有帮助。保持乐观心态。",
         "人际关系非常融洽，容易结交新朋友。适合参加聚会和社交活动。"),
    32: ("感情上强调持久和稳定。不要追求轰轰烈烈，细水长流才是真。有伴侣者共同经营，单身者耐心等待。",
         "事业上坚持做正确的事，不要频繁跳槽或换方向。持之以恒终会看到成果。",
         "财运适合长期投资。坚持定投，不要追涨杀跌。时间是财富的朋友。",
         "身体需要长期保持健康习惯。运动和饮食要成为生活方式，而非短期行为。",
         "人际关系要维护长久的友谊。定期联系老朋友，不要等到需要帮忙才想起人家。"),
    33: ("感情上可能需要暂时退一步。给彼此一些空间和时间，冷静思考这段关系的未来。",
         "事业上可能需要战略性退让。暂时的退步是为了更好的前进，不要逞强。",
         "财运上保守为宜。减少不必要的开支，保存现金实力。",
         "身体需要休息和恢复。不要硬撑，该休息就休息。",
         "人际交往暂时减少应酬。给自己一些独处时间，恢复社交能量。"),
    34: ("感情上力量充沛但要注意控制。不要因为强势而吓跑对方。温柔的力量比霸道更有吸引力。",
         "事业上能量充沛，适合大展拳脚。但要确保力量用在正确的地方，不要恃强凌弱。",
         "财运不错，但不要因为手头宽裕就大手大脚。保持理性消费。",
         "身体精力旺盛，适合运动锻炼。但要防止运动过量导致受伤。",
         "人际关系中你有很强的影响力。用这份力量去帮助他人，而非压制他人。"),
    35: ("感情上运势上升，魅力增强。单身者桃花运好，有伴侣者关系升温。把握机会表达爱意。",
         "事业上处于上升期，适合争取晋升或新机会。你的能力正在被看到和认可。",
         "财运稳中有升，正财收入有望增加。适合做中长期投资规划。",
         "身体状态良好，精力充沛。保持当前的健康习惯，会越来越好。",
         "人际关系和谐，社交运好。适合拓展人脉，参加各类社交活动。"),
    36: ("感情上可能遭遇不公正的对待或误解。保持内心的光明，不要因为外在的困境而放弃对爱的信念。",
         "事业上可能被低估或埋没。韬光养晦，默默提升自己，等待重新被发现的时机。",
         "财运可能有暂时的损失或不顺。保守理财，不要做冒险投资。",
         "身体可能有隐性的健康问题。定期体检，不要忽视任何不适信号。",
         "人际交往中可能遇到误解或背叛。保持警觉，但不要因此封闭自己。"),
    37: ("感情上家庭和谐是基础。处理好与家人的关系，才能有更好的感情运。",
         "事业上家人的支持很重要。平衡工作和家庭，不要因为工作忽略了家人。",
         "财运上家庭理财很重要。与伴侣共同规划财务，家庭收支要透明。",
         "身体上家庭的照顾很关键。注意家人的健康，互相督促保持健康习惯。",
         "人际关系中要重视家庭关系。多花时间陪伴家人，家庭和睦是一切的基础。"),
    38: ("感情上可能与伴侣有分歧或对立。求同存异是关键，不要因为小事伤了和气。",
         "事业上可能与同事或上级意见不合。保持冷静，寻找共同点，避免正面冲突。",
         "财运上可能有投资方向的分歧。与理财顾问或伴侣充分沟通后再做决定。",
         "身体上可能有内分泌或免疫系统的小问题。注意调节情绪，保持平和心态。",
         "人际交往中可能遇到立场不同的人。尊重差异，求同存异。"),
    39: ("感情上前进受阻，不宜强求。反思自身不足，调整策略后再行动。",
         "事业上遇到瓶颈，不宜冒进。寻求导师或前辈的建议，迂回前进。",
         "财运上投资不宜激进。保守理财，等待更好的机会。",
         "身体上可能有慢性问题需要关注。不要讳疾忌医，及时调理。",
         "出行注意安全，不宜远行。人际交往中寻求帮助，不要独自承担。"),
    40: ("感情上的困难正在化解。之前的误会或冷淡会逐渐消除，关系回暖。",
         "事业上的阻碍正在消散。之前卡住的项目会有所突破，抓紧时间推进。",
         "财运上的困局正在打开。可能有回款或收入到账，财务状况改善。",
         "身体上的不适正在好转。坚持调养，健康会逐步恢复。",
         "人际关系中的矛盾正在化解。主动沟通，修复受损的关系。"),
    41: ("感情上需要适当的付出和牺牲。不要太计较得失，真心的付出终会得到回报。",
         "事业上需要投入更多精力。短期的辛苦会换来长期的收获。",
         "财运上可能需要先付出才能获得回报。投资自己（学习、技能）是最好的投资。",
         "身体上需要适当控制饮食和作息。有节制的生活带来更好的健康。",
         "人际关系中需要主动付出。真诚地帮助他人，好的人际关系自然而来。"),
    42: ("感情上运势上升，付出和回报都在增长。适合主动追求心仪的对象，表达爱意。",
         "事业上处于上升期，适合大胆行动。之前的努力开始有回报，乘胜追击。",
         "财运明显好转，收入有望增加。适合做投资规划，把握增长机会。",
         "身体状态良好，精力充沛。保持运动习惯，健康运持续向好。",
         "人际关系和谐，贵人运旺。多与优秀的人交往，互相成就。"),
    43: ("感情上需要果断处理积压的问题。不要回避矛盾，直面问题才能解决。",
         "事业上积压已久的难题需要一个痛快的解决。果断行动，但注意方式方法。",
         "财运上需要清理不良资产或债务。果断处理财务问题，轻装上阵。",
         "身体上积累的健康隐患需要正视。该体检体检，该治疗治疗。",
         "人际交往中需要果断处理不良关系。该断则断，不要拖泥带水。"),
    44: ("感情上可能遇到意想不到的人。保持警惕，分辨真心与诱惑。不是所有的相遇都是良缘。",
         "事业上可能遇到意外的机会或挑战。保持清醒头脑，不要被表面现象迷惑。",
         "财运上可能有意外的收入或支出。保持理性，不要被诱惑冲昏头脑。",
         "身体上可能出现突发状况。注意安全，定期体检。",
         "人际交往中注意分辨真假朋友。不要轻易相信陌生人的示好。"),
    45: ("感情上适合参加集体活动结识新朋友。在人群中你更容易找到志同道合的伴侣。",
         "事业上团队合作很重要。参加行业活动，拓展职业人脉。",
         "财运上通过人脉和合作可能获得不错的收入机会。",
         "身体上与朋友一起运动效果更好。找个运动伙伴互相督促。",
         "人际关系非常适合社交。参加聚会、社团活动，扩大社交圈。"),
    46: ("感情上关系稳步上升。像树木生长一样，感情在不知不觉中变得深厚。",
         "事业上处于稳步上升期。继续努力，你的能力正在被认可。",
         "财运稳中有升。坚持储蓄和投资计划，财富会慢慢积累。",
         "身体状态稳步改善。坚持健康习惯，效果会越来越明显。",
         "人际关系越来越好。你的人格魅力正在吸引越来越多的朋友。"),
    47: ("感情上可能感到受限或被困。但困境是暂时的，坚持下去会有转机。",
         "事业上可能感到施展不开。不要灰心，提升自己的能力，等待机会。",
         "财运上可能有资金周转困难。节约开支，寻求帮助，渡过难关。",
         "身体上可能感到疲惫或不适。注意休息，不要硬撑。",
         "人际交往中可能感到孤独。主动联系朋友，不要把自己封闭起来。"),
    48: ("感情上要找到源源不断的情感来源。不要只依赖一个人，培养多元的情感支持系统。",
         "事业上要找到持续学习和成长的源泉。保持学习热情，不断充电。",
         "财运上要建立稳定的收入来源。不要依赖单一收入，发展多元收入渠道。",
         "身体上要注意持续保养。健康不是一朝一夕的事，需要长期坚持。",
         "人际关系中要维护好核心朋友圈。定期联系，不要让友谊变淡。"),
    49: ("感情上可能需要做出重大改变。旧的相处模式不再适用，需要创新和突破。",
         "事业上需要变革和创新。旧的工作方式已经过时，拥抱变化才能进步。",
         "财运上需要调整理财策略。旧的赚钱方式可能不再有效，寻找新的收入来源。",
         "身体上需要改变不良的生活习惯。健康问题往往源于长期的坏习惯。",
         "人际交往中需要更新社交方式。适应新的社交环境，拓展新的交友圈。"),
    50: ("感情上经历转化和升华。关系从一种形态转变为更成熟、更深层的形态。",
         "事业上经历重要的转型期。你的专业能力正在从量变到质变。",
         "财运上经历财务结构的优化。不合理的消费和投资正在被调整。",
         "身体上经历健康状态的改善。不良的生活方式正在被更健康的选择取代。",
         "人际交往中社交质量在提升。无效社交在减少，有价值的友谊在加深。"),
    51: ("感情上可能有突然的惊喜或冲击。保持冷静，不要被情绪左右。变化虽突然但也是成长的契机。",
         "事业上可能有突发变动。保持灵活，随机应变，化危为机。",
         "财运上可能有意外的收入或支出。保持现金储备，应对不确定性。",
         "身体上注意突发状况。保持急救意识，随身携带常用药。",
         "人际交往中可能有意外的相遇或冲突。保持冷静理性，妥善处理。"),
    52: ("感情上需要静下心来思考。不要急于行动，先理清自己的内心。独处和冥想有助于感情的明朗。",
         "事业上需要暂停忙碌，反思方向。有时候停下来思考比盲目前进更重要。",
         "财运上需要冷静分析财务状况。不要冲动消费或投资，先做好规划。",
         "身体上需要静养和休息。适合做冥想、瑜伽等静心活动。",
         "人际交往中暂时减少社交，给自己一些安静的空间。"),
    53: ("感情上循序渐进是最好的策略。不要急于确定关系，让感情自然发展。水到渠成比强求更有效。",
         "事业上按部就班地推进。不要急于求成，扎实的基础比速度更重要。",
         "财运上稳扎稳打。坚持储蓄计划，不要追求暴利。",
         "身体上慢慢建立健康习惯。不要一下子改变太多，循序渐进。",
         "人际关系慢慢培养。真诚和时间是最好的社交策略。"),
    54: ("感情上可能有一段新的关系开始，但要认清现实。不是所有的开始都有完美结局，保持清醒。",
         "事业上新的合作或项目开始，但要评估风险。不要被表面的光鲜迷惑。",
         "财运上可能有新的投资机会，但要仔细评估。不要被高收益承诺诱惑。",
         "身体上新的健康计划开始执行。坚持下去，效果会慢慢显现。",
         "人际交往中新的友谊正在建立。保持真诚，但也要观察对方的品性。"),
    55: ("感情上处于最丰盛的时期。珍惜当下的幸福，但也要居安思危，为未来做准备。",
         "事业上处于巅峰期。把握机会大展宏图，但也要为可能的衰退做准备。",
         "财运上非常旺盛。把握赚钱机会，但不要因为赚得多就花得多。",
         "身体上精力充沛。保持健康习惯，不要因为状态好就放纵。",
         "人际关系非常活跃。珍惜身边的朋友，不要因为忙碌忽略了他们。"),
    56: ("感情上在陌生环境中需要谨慎。不要因为孤独而随便开始一段感情。",
         "事业上在新环境中需要适应。保持谦虚低调，尊重当地的规则和文化。",
         "财运上在陌生环境中要保守理财。不要因为环境变化就改变理财策略。",
         "身体上在新环境中注意适应。注意饮食和气候的变化。",
         "人际交往中在新环境中要谨慎交友。先观察再交往，不要急于信任。"),
    57: ("感情上用柔和的方式影响对方。不要硬碰硬，以柔克刚才是上策。",
         "事业上用柔和的方式推进工作。不要与上级正面冲突，迂回达成目标。",
         "财运上稳健理财，不急不躁。细水长流比一夜暴富更可靠。",
         "身体上温和调养。不要做剧烈运动，适合太极、瑜伽等柔和运动。",
         "人际交往中以柔和的方式建立关系。真诚和耐心是最好的社交策略。"),
    58: ("感情上充满喜悦和甜蜜。适合表白、约会或庆祝纪念日。分享快乐会让感情更深厚。",
         "事业上心情愉悦，工作效率高。适合团队合作和创意工作。",
         "财运上有不错的偏财运。可能有意外的收入或礼物。",
         "身体上心情好是最好的保健品。保持乐观心态，健康自然来。",
         "人际关系非常融洽。适合参加聚会，与朋友分享快乐。"),
    59: ("感情上的隔阂正在消散。之前的距离感会逐渐消除，关系变得更加亲密。",
         "事业上团队的凝聚力在恢复。之前分散的力量正在重新聚合。",
         "财运上资金流动恢复正常。之前冻结或卡住的资金开始流通。",
         "身体上的不适正在消散。精神状态好转，身体也会跟着好转。",
         "人际关系中的隔阂正在消除。主动联系，重建联系。"),
    60: ("感情上要把握分寸。不要太黏人也不要太冷淡，找到合适的距离感。",
         "事业上要把握工作和休息的平衡。过度工作或过度放松都不好。",
         "财运上要节制消费。量入为出，不要铺张浪费。",
         "身体上要有节制的生活。饮食有度，运动适量，作息规律。",
         "人际交往中要有分寸感。不要过度依赖他人，也不要完全孤立。"),
    61: ("感情上以真心换真心。真诚是建立信任的基础，不要玩心机或套路。",
         "事业上以诚信赢得信任。言行一致，说到做到，自然会获得同事和上级的信任。",
         "财运上诚信理财。不要走歪门邪道，正当的收入才长久。",
         "身体上真心对待自己的身体。不要为了工作或社交牺牲健康。",
         "人际交往中真心待人。真诚的朋友不需要你刻意讨好。"),
    62: ("感情上小事不拘，大事谨慎。日常的小浪漫可以大胆，但涉及未来的重大决定要慎重。",
         "事业上小事灵活处理，大事格外谨慎。细节上可以大胆创新，方向上要慎重。",
         "财运上小额支出可以大方，大额投资要谨慎。不要因小失大。",
         "身体上日常保健可以灵活，但重大健康决定要咨询专业医生。",
         "人际交往中小事随和，大事有原则。随和但不随便。"),
    63: ("感情上已经达到了一个圆满的阶段。但圆满之后要居安思危，为下一个阶段做准备。",
         "事业上已经取得了不错的成果。但不要止步不前，要为下一个目标做准备。",
         "财运上已经积累了一定的财富。做好资产配置，为长期增长做准备。",
         "身体上健康状态良好。保持当前的健康习惯，预防胜于治疗。",
         "人际关系已经很稳固。珍惜身边的朋友，同时也要拓展新的社交圈。"),
}

_FORTUNE_EN = {
    23: ("You may experience a cool period in love. Be patient — don't make important relationship decisions when feeling down. Singles should focus on self-improvement first.",
         "Career may hit a bottleneck or face resource shortages. Hold your position, build strength, and wait for the right moment.",
         "Finances are weak — avoid investments and large purchases. Save money and control spending until fortune recovers.",
         "Easily fatigued with lowered immunity. Rest well, avoid overwork, and get regular check-ups.",
         "Social circles may feel distant. Solitude and reflection help restore your inner energy."),
    24: ("Love takes a new turn for the better. Cold relationships may warm up; singles may encounter new romantic opportunities. Act, but don't rush.",
         "Previously stalled projects may restart. Seize the revival opportunity — act decisively but steadily.",
         "Finances begin to recover. Small unexpected income may appear. Start saving and financial planning.",
         "Health bounces back from a low point. Energy gradually returns. Resume regular exercise and healthy habits.",
         "Social connections warm up. Reconnect with distant friends. Join social events to expand your network."),
    25: ("You may encounter unexpected people or events in love. Stay genuine and natural — forced behaviour backfires. Let things flow.",
         "Career may bring unexpected changes or opportunities. Stay calm and don't let surprises disrupt your rhythm.",
         "Finances fluctuate unexpectedly — possible surprise expenses or income. Stay rational in spending.",
         "Minor sudden health issues may appear but aren't serious. Watch hygiene and maintain regular routines.",
         "Travel may have small bumps but is generally safe. Stay flexible and adapt to changes."),
    26: ("Love needs slow cultivation — don't rush. Take time to deeply understand your partner and build a solid foundation.",
         "Career is in an accumulation phase — job-hopping or entrepreneurship isn't ideal. Deepen your expertise.",
         "Long-term investing and saving suit you now. Avoid short-term trading; stick to dollar-cost averaging.",
         "Your body needs care. Get a comprehensive check-up. Watch your gut health and eat regularly.",
         "Deep conversations with like-minded people suit you. Less small talk, more meaningful dialogue."),
    27: ("Watch that your words match your actions. Sincerity is the best love strategy. Choose healthy social environments.",
         "Choose the right learning path. Following the right mentor and industry matters more than raw effort.",
         "Choose sound financial methods. Learn basic financial knowledge and avoid scams.",
         "Diet and food safety matter — illness enters through the mouth. Watch nutrition and food quality.",
         "Choose virtuous friends. Distance negative people and surround yourself with positive influences."),
    28: ("Love may face unusual pressures. You need courage to face and handle extraordinary situations in your relationship.",
         "Career faces major challenges requiring unconventional solutions. Gather courage to break through.",
         "Finances may face significant pressure or risk. Be cautious — don't put all eggs in one basket.",
         "Your body shows signs of serious overexpenditure. Priorise health and seek medical help when needed.",
         "Social relationships may present thorny issues. Stay calm, rational, and seek professional advice."),
    29: ("Love may go through trials. Don't make major romantic decisions during tough times. Integrity and courage will see you through.",
         "Career faces risks and challenges. Act cautiously, avoid gambles, and seek help when stuck.",
         "Finances carry risk of loss. Invest conservatively and avoid high-risk ventures.",
         "Hidden health concerns may lurk. Get regular check-ups and address issues promptly — don't delay.",
         "Travel safely and avoid risky activities. Be wary of false friends and stay alert."),
    30: ("Find the right partner to lean on — someone who lets you shine and whom you can uplift in return.",
         "Find the right platform and direction. Lean on good teams and leaders to let your light shine.",
         "You need reliable financial channels. Choose trustworthy investment avenues — don't follow trends blindly.",
         "You need a proper lifestyle foundation. Build healthy routines for sleep and diet.",
         "Seek truly worthwhile friends. Treat them sincerely and build solid, lasting friendships."),
    31: ("Emotional resonance and attraction come easily. Good time to confess feelings or confirm a relationship. Intuition is especially strong.",
         "Support and help from others come easily. Harmonious relationships make teamwork smooth.",
         "Social connections bring financial opportunities. Cooperation and networking may yield good income.",
         "You feel good — a happy mood greatly benefits health. Keep a positive outlook.",
         "Social harmony is excellent. Easy to make new friends. Join gatherings and social events."),
    32: ("Love emphasises endurance and stability. Slow and steady wins — don't chase drama. Couples nurture together; singles wait patiently.",
         "Persist in doing the right thing. Don't jump ship frequently — perseverance brings results.",
         "Long-term investing suits you. Stick to regular contributions; time is wealth's best friend.",
         "Maintain healthy habits long-term. Exercise and diet should become lifestyle, not short-term fixes.",
         "Maintain long-term friendships. Contact old friends regularly — don't wait until you need them."),
    33: ("You may need to step back temporarily. Give each other space and time to think calmly about the relationship's future.",
         "Strategic retreat may be needed. Temporary stepping back enables better forward progress later.",
         "Be conservative with finances. Cut unnecessary expenses and preserve cash reserves.",
         "Rest and recover. Don't push through — rest when your body tells you to.",
         "Reduce social obligations temporarily. Give yourself quiet time to recharge social energy."),
    34: ("You're full of romantic energy but must control it. Don't overwhelm your partner with dominance. Gentle strength is more attractive.",
         "Energy is abundant — ideal for bold action. But ensure force is directed correctly, not abused.",
         "Finances are decent, but don't splurge just because you can. Spend rationally.",
         "Physical energy is high — great for exercise. But guard against overexertion and injury.",
         "You have strong social influence. Use it to help others, not to dominate them."),
    35: ("Love fortune rises — charm increases. Singles enjoy good romantic luck; couples' bond deepens. Seize the moment to express love.",
         "Career is on the upswing — good time to pursue promotions or new opportunities. Your abilities are being recognised.",
         "Finances steadily improve with growth in regular income. Plan medium-to-long-term investments.",
         "Health is strong with abundant energy. Maintain current healthy habits and things will only improve.",
         "Social life is harmonious with good networking luck. Expand connections and attend social events."),
    36: ("You may face unfair treatment or misunderstanding in love. Keep your inner light — don't abandon belief in love due to external hardship.",
         "Your talents may be overlooked. Keep a low profile, quietly improve yourself, and wait to be discovered again.",
         "Temporary financial losses or setbacks may occur. Invest conservatively — avoid risky ventures.",
         "Hidden health issues may exist. Get regular check-ups and don't ignore any warning signs.",
         "You may encounter betrayal or misunderstanding socially. Stay alert but don't close yourself off."),
    37: ("Family harmony is the foundation. Good family relationships support better love fortune.",
         "Family support matters at work. Balance career and family — don't neglect loved ones for your job.",
         "Family financial planning is important. Plan finances transparently with your partner.",
         "Family care is key to health. Pay attention to family members' wellbeing and encourage healthy habits together.",
         "Prioritise family relationships. Spend quality time with family — domestic harmony underpins everything."),
    38: ("Disagreements with your partner may arise. Seeking common ground while respecting differences is key.",
         "You may disagree with colleagues or superiors. Stay calm, find common ground, and avoid direct confrontation.",
         "Financial investment opinions may differ. Communicate fully with advisors or your partner before deciding.",
         "Minor endocrine or immune issues may surface. Regulate emotions and maintain inner peace.",
         "You'll encounter people with different viewpoints. Respect differences and seek common ground."),
    39: ("Love progress is blocked — don't force it. Reflect on your own shortcomings, adjust strategy, then act.",
         "Career hits a bottleneck — don't rush in. Seek advice from mentors or seniors; take a roundabout path.",
         "Avoid aggressive investments. Invest conservatively and wait for better opportunities.",
         "Chronic health issues may need attention. Don't avoid the doctor — seek timely treatment.",
         "Travel safely and avoid long trips. Seek help socially — don't shoulder everything alone."),
    40: ("Relationship difficulties are dissolving. Previous misunderstandings or coldness will gradually fade, and warmth returns.",
         "Career obstacles are clearing. Previously stalled projects will break through — act quickly.",
         "Financial difficulties are opening up. Payments may arrive and your financial situation improves.",
         "Physical discomfort is improving. Continue care and health will gradually recover.",
         "Social conflicts are resolving. Communicate proactively to repair damaged relationships."),
    41: ("Love requires appropriate giving and sacrifice. Don't keep score — sincere giving brings returns.",
         "Career needs more effort invested. Short-term hardship leads to long-term reward.",
         "You may need to give before receiving. Investing in yourself (learning, skills) is the best investment.",
         "Moderate your diet and routine. A restrained lifestyle brings better health.",
         "Take initiative in relationships. Sincerely help others and good connections will follow naturally."),
    42: ("Love fortune rises — both giving and receiving increase. Good time to pursue someone and express your feelings.",
         "Career is ascending — act boldly. Previous efforts are paying off; press your advantage.",
         "Finances improve significantly with income growth likely. Plan investments and seize growth opportunities.",
         "Health is strong with abundant energy. Maintain exercise habits; health fortune keeps improving.",
         "Social harmony with strong mentor luck. Spend time with excellent people — lift each other up."),
    43: ("Love requires decisiveness in addressing accumulated issues. Don't avoid conflict — face problems head-on.",
         "Long-pending career problems need decisive resolution. Act firmly, but choose your method wisely.",
         "Clear up bad assets or debts. Handle financial issues decisively and start fresh.",
         "Accumulated health risks must be faced. Get check-ups, get treatment — don't procrastinate.",
         "Handle toxic relationships decisively. Cut cleanly — don't drag things out."),
    44: ("You may encounter unexpected people in love. Stay vigilant — distinguish genuine interest from temptation. Not every encounter is a blessing.",
         "Unexpected career opportunities or challenges may appear. Stay clear-headed; don't be fooled by appearances.",
         "Surprise income or expenses may occur. Stay rational — don't let temptation cloud your judgement.",
         "Sudden health situations may arise. Stay safe and get regular check-ups.",
         "Distinguish real friends from false ones socially. Don't easily trust strangers' friendliness."),
    45: ("Group activities are great for meeting new romantic prospects. You're more likely to find a like-minded partner among people.",
         "Teamwork matters. Attend industry events and expand professional networks.",
         "Social connections may bring good income opportunities through cooperation.",
         "Exercising with friends is more effective. Find a workout buddy for mutual motivation.",
         "Social life is excellent. Join gatherings, clubs, and activities to widen your circle."),
    46: ("Love grows steadily upward. Like a tree growing, deepening imperceptibly in everyday moments.",
         "Career steadily ascends. Keep going — your abilities are being recognised.",
         "Finances gradually improve. Stick to savings and investment plans; wealth accumulates slowly.",
         "Health steadily improves. Maintain healthy habits and the results become more and more obvious.",
         "Social life improves continually. Your personal charm attracts more and more friends."),
    47: ("You may feel trapped or constrained in love. But hardship is temporary — persistence brings a turning point.",
         "Career may feel stifled. Don't lose heart — improve your skills and wait for opportunity.",
         "Cash flow difficulties may arise. Cut expenses, seek help, and ride out the storm.",
         "Fatigue or discomfort may set in. Rest properly — don't push through.",
         "Loneliness may creep in socially. Reach out to friends; don't isolate yourself."),
    48: ("Find a continuous source of emotional nourishment. Don't rely on just one person — build diverse emotional support.",
         "Find a lasting source of learning and growth. Keep your passion for learning alive.",
         "Build stable income sources. Don't depend on a single stream — develop diversified income.",
         "Sustain ongoing health maintenance. Health isn't built in a day — it requires long-term commitment.",
         "Maintain your core friend circle. Contact them regularly — don't let friendships fade."),
    49: ("Love may need a major change. Old patterns no longer work — innovation and breakthrough are needed.",
         "Career demands transformation and innovation. Old methods are outdated — embrace change to progress.",
         "Financial strategies need adjustment. Old money-making methods may no longer work — seek new sources.",
         "Bad lifestyle habits need changing. Health problems often stem from long-term unhealthy choices.",
         "Social methods need updating. Adapt to new environments and expand into new social circles."),
    50: ("Love undergoes transformation and elevation. The relationship shifts into a more mature, deeper form.",
         "Career enters an important transition. Your professional ability is transforming from quantity to quality.",
         "Financial structure is optimising. Unreasonable spending and investments are being adjusted.",
         "Health is improving. Unhealthy lifestyles are being replaced by better choices.",
         "Social quality is rising. Ineffective socialising decreases while valuable friendships deepen."),
    51: ("Sudden surprises or shocks may hit love. Stay calm — don't let emotions dictate. Change, though sudden, is a growth opportunity.",
         "Sudden career changes may occur. Stay flexible, adapt, and turn crisis into opportunity.",
         "Unexpected income or expenses may hit. Maintain cash reserves to handle uncertainty.",
         "Watch for sudden health events. Stay first-aid aware and carry common medications.",
         "Unexpected social encounters or conflicts may arise. Stay calm and handle them properly."),
    52: ("Take time to reflect on love before acting. Don't rush — sort out your inner feelings first. Solitude and meditation bring clarity.",
         "Pause the busyness and reflect on direction. Sometimes stopping to think matters more than blind progress.",
         "Calmly analyse your financial situation. Don't impulse-spend or invest — plan first.",
         "Rest and recuperate. Meditation, yoga, and quiet activities suit you now.",
         "Reduce socialising temporarily. Give yourself some quiet, personal space."),
    53: ("Gradual progress is the best love strategy. Don't rush to define the relationship — let it develop naturally.",
         "Advance methodically. Solid foundations matter more than speed.",
         "Invest steadily. Stick to your savings plan — don't chase quick riches.",
         "Build healthy habits gradually. Don't change everything at once — take it step by step.",
         "Nurture relationships slowly. Sincerity and time are the best social strategies."),
    54: ("A new relationship may begin, but see reality clearly. Not every beginning has a perfect ending — stay clear-headed.",
         "New collaborations or projects start, but assess the risks. Don't be dazzled by surface glamour.",
         "New investment opportunities may appear, but evaluate carefully. Don't be tempted by high-return promises.",
         "A new health plan begins execution. Persist and results will gradually show.",
         "New friendships are forming. Stay sincere, but also observe the other person's character."),
    55: ("Love is at its most abundant. Cherish current happiness, but prepare for the future — enjoy prosperity while staying vigilant.",
         "Career is at its peak. Seize the opportunity for grand achievements, but prepare for possible decline.",
         "Finances are very strong. Capitalise on earning opportunities, but don't let high income lead to high spending.",
         "Energy is abundant. Maintain healthy habits — don't indulge just because you feel great.",
         "Social life is very active. Cherish your friends; don't let busyness cause you to neglect them."),
    56: ("Be cautious in unfamiliar romantic environments. Don't start a relationship just because of loneliness.",
         "Adapt to new work environments. Stay humble, low-key, and respect local rules and culture.",
         "Be conservative with finances in unfamiliar settings. Don't change your financial strategy due to environment changes.",
         "Adapt your body to new environments. Watch for changes in diet and climate.",
         "Be cautious making new friends in unfamiliar settings. Observe first, then engage — don't rush to trust."),
    57: ("Influence your partner gently. Soft persistence is more effective than forceful demands.",
         "Advance work through gentle means. Don't confront superiors directly — achieve goals indirectly.",
         "Invest steadily and patiently. Slow and steady is more reliable than get-rich-quick schemes.",
         "Nurture health gently. Avoid intense exercise — tai chi, yoga, and gentle movement suit you.",
         "Build relationships through gentle sincerity. Patience and authenticity are the best social tools."),
    58: ("Love is full of joy and sweetness. Perfect for confessions, dates, or celebrating anniversaries. Sharing happiness deepens bonds.",
         "A happy mood boosts work efficiency. Teamwork and creative work go especially well.",
         "Good windfall luck — possible surprise income or gifts.",
         "A good mood is the best health tonic. Maintain optimism and health follows naturally.",
         "Social harmony is excellent. Join parties and share joy with friends."),
    59: ("Emotional barriers are dissolving. Previous distance will gradually fade and intimacy deepens.",
         "Team cohesion is recovering. Previously scattered forces are reuniting.",
         "Cash flow normalises. Previously frozen or stuck funds start moving again.",
         "Discomfort is fading. Mental state improves, and the body follows.",
         "Social barriers are dissolving. Reach out and rebuild connections."),
    60: ("Find the right balance in love — neither too clingy nor too cold. The sweet spot is key.",
         "Balance work and rest. Neither overworking nor over-relaxing serves you.",
         "Exercise spending discipline. Live within your means — don't be extravagant.",
         "Live with moderation. Eat moderately, exercise适量, and keep regular hours.",
         "Maintain social boundaries. Don't over-rely on others, but don't isolate yourself either."),
    61: ("Exchange sincerity for sincerity. Trust is built on authenticity — don't play games or use tricks.",
         "Win trust through integrity. Say what you mean and mean what you say — colleagues and superiors will trust you.",
         "Be honest in financial dealings. Illicit gains don't last — legitimate income endures.",
         "Treat your body honestly. Don't sacrifice health for work or social obligations.",
         "Be genuine with people. True friends don't require you to ingratiate yourself."),
    62: ("In love, be relaxed about small things but careful about big ones. Daily romance can be bold; major future decisions need慎重.",
         "Handle small matters flexibly, but be extra cautious with big decisions. Innovate in details, be careful with direction.",
         "Small expenses can be generous; large investments need caution. Don't lose big for small gains.",
         "Daily health care can be flexible, but major health decisions need professional medical advice.",
         "Be easy-going on small social matters, but maintain principles on big ones. Flexible, not careless."),
    63: ("Love has reached a fulfilling stage. But after fulfilment, stay vigilant — prepare for the next chapter.",
         "Career has achieved good results. Don't rest on your laurels — prepare for the next goal.",
         "Wealth has accumulated nicely. Configure assets wisely and prepare for long-term growth.",
         "Health is in good shape. Maintain current healthy habits — prevention is better than cure.",
         "Social bonds are solid. Cherish your friends while also expanding into new social circles."),
}

_FORTUNE_TITLES = {
    "love": _titles("恋爱运势","恋愛運勢","Love Fortune","Vận tình cảm","연애운","ချစ်ခြင်းမေတ္တာ"),
    "career": _titles("事业运势","事業運勢","Career Fortune","Vận sự nghiệp","직업운","အလုပ် / ပညာရေး"),
    "wealth": _titles("财运","金運","Wealth Fortune","Vận tài chính","재운","ငွေကြေး"),
    "health": _titles("健康运势","健康運勢","Health Fortune","Vận sức khỏe","건강운","ကျန်းမာရေး"),
    "travel": _titles("人际运势","人間運勢","People Fortune","Vận nhân tế","대인운","လူမှုဆက်ဆံရေး"),
}


_GLOSSARY = {
    "zh": {
        "动爻": "动爻是指在起卦过程中发生变化的爻（线条），代表事物正在转变的关键点。",
        "本卦": "本卦是起卦得到的原始卦象，代表事物当前的状态。",
        "变卦": "变卦是动爻变化后形成的新卦象，代表事物的未来走向。",
        "六亲": "六亲是六爻预测中的亲缘关系系统，包括父母、兄弟、妻财、子孙、官鬼五种关系。",
        "用神": "用神是六爻预测中代表所问之事的核心要素，是解读卦象的关键。",
        "阳爻": "阳爻是一条完整的横线（—），代表阳刚、主动、外向的力量。",
        "阴爻": "阴爻是中间断开的横线（- -），代表阴柔、被动、内敛的力量。",
    },
    "en": {
        "动爻": "Moving Line (Dong Yao): A line that changes during casting, representing a key point of transformation.",
        "本卦": "Original Hexagram (Ben Gua): The hexagram obtained from casting, representing the current situation.",
        "变卦": "Changed Hexagram (Bian Gua): The new hexagram formed after moving lines change, showing future direction.",
        "六亲": "Six Relations (Liu Qin): A kinship system in Six Yao prediction including Parents, Siblings, Wife/Wealth, Children, and Officials.",
        "用神": "Useful Spirit (Yong Shen): The core element in Six Yao reading that represents the matter being asked about.",
        "阳爻": "Yang Line: A solid unbroken line representing active, masculine, outward energy.",
        "阴爻": "Yin Line: A broken line representing receptive, feminine, inward energy.",
    },
    "ja": {
        "動爻": "動爻（どうこう）：変化する爻で、事物が転換する要点を表します。",
        "本卦": "本卦（ほんか）：占いで得た元の卦で、現在の状態を表します。",
        "変卦": "変卦（へんか）：動爻が変化して生まれた新しい卦で、将来の流れを表します。",
        "六親": "六親（りくしん）：六爻予測の親縁関係システムで、父母・兄弟・妻財・子孫・官鬼の五つ。",
        "用神": "用神（ようしん）：六爻予測で質問事項を代表する核心要素。",
    },
    "vi": {
        "Hào động": "Hào động (Hào chuyển): Là hào thay đổi khi gieo quẻ, đại diện cho điểm chuyển then chốt của sự việc.",
        "Quẻ gốc": "Quẻ gốc (Bản quẻ): Quẻ ban đầu khi gieo, đại diện cho hiện trạng sự việc.",
        "Quẻ biến": "Quẻ biến: Quẻ mới hình thành sau khi hào động chuyển, cho thấy xu hướng tương lai.",
        "Lục thân": "Lục thân: Hệ thống quan hệ thân thích trong dự đoán Lục Hào, gồm Phụ mẫu, Huynh đệ, Thê tài, Tử tôn, Quan quỷ.",
        "Dụng thần": "Dụng thần: Yếu tố cốt lõi đại diện cho điều muốn hỏi trong phân tích Lục Hào.",
    },
    "ko": {
        "동효": "동효(動爻): 점을 칠 때 변화하는 효로, 사물이 전환되는 핵심 지점을 나타냅니다.",
        "본괘": "本卦: 점에서 얻은 원래 괘으로, 현재 상태를 나타냅니다.",
        "변괘": "変卦: 동효가 변화하여 형성된 새로운 괘으로, 미래 흐름을 나타냅니다.",
        " 육신": "六親: 육효 예측의 친족 관계 시스템으로, 부모·형제·처재·자손·관귀의 다섯 가지.",
        "용신": "用神: 육효 예측에서 질문 사항을 대표하는 핵심 요소.",
    },
    "my": {
        "လှုပ်ရှားသည့်အကြောင်းအရာ": "လှုပ်ရှားသည့်အကြောင်းအရာ — ပြောင်းလဲနေသည့် အကြောင်းအရာဖြစ်ပြီး အရာဝတ္ထု၏ အဓိကပြောင်းလဲမှုအမှတ်ကို ကိုယ်စားပြုသည်။",
        "မူလဗေဒ": "မူလဗေဒ — လှည့်ခြင်းမှ ရရှိသည့် မူလဗေဒဖြစ်ပြီး လက်ရှိအခြေအနေကို ကိုယ်စားပြုသည်။",
        "ပြောင်းလဲသည့်ဗေဒ": "ပြောင်းလဲသည့်ဗေဒ — လှုပ်ရှားသည့်အကြောင်းအရာ ပြောင်းလဲပြီးနောက် ဖြစ်ပေါ်လာသည့် ဗေဒအသစ်ဖြစ်ပြီး အနာဂတ် လမ်းကြောင်းကို ပြသသည်။",
        "ဆွေမျိုး ၆ ပါး": "ဆွေမျိုး ၆ ပါး — ဆြေရှုရေးခန့်မှန်းခြင်းတွင် အသုံးပြုသည့် ဆွေမျိုးဆက်ဆံရေးစနစ်ဖြစ်ပြီး မိဘ၊ ညီအစ်ကိုမောင်နှမ၊ ဇနီး/ငွေကြေး၊ သားသမီး၊ အရာရှိ ဟူသော ဆက်ဆံရေး ၅ မျိုး ပါဝင်သည်။",
        "အသုံးဝင်သည့်စိတ်တန်ခိုး": "အသုံးဝင်သည့်စိတ်တန်ခိုး — ဆြေရှုရေးဖတ်ခြင်းတွင် မေးခွန်းကို ကိုယ်စားပြုသည့် အဓိကအချက်အလက်ဖြစ်သည်။",
        "အမျိုးသားအကြောင်းအရာ": "အမျိုးသားအကြောင်းအရာ — မပြတ်တောက်သည့် မျဉ်းဖြစ်ပြီး အမျိုးသား၊ တက်ကြွသည့်၊ အပြင်ဘက် စွမ်းအင်ကို ကိုယ်စားပြုသည်။",
        "အမျိုးသမီးအကြောင်းအရာ": "အမျိုးသမီးအကြောင်းအရာ — ပြတ်တောက်သည့် မျဉ်းဖြစ်ပြီး လက်ခံနိုင်မှု၊ အတွင်းပိုင်း စွမ်းအင်ကို ကိုယ်စားပြုသည်။",
    },
}


def _get_overall_translations(hex_code):
    """Get the overall desc translations for a hexagram (used as fallback for ja/vi/ko)."""
    data = _HEX_DATA.get(hex_code, {})
    if len(data) >= 10:
        return {"ja": data[6], "en": data[7], "vi": data[8], "ko": data[9]}
    return {}


for code, data in _HEX_DATA.items():
    if code in INTERPRETATIONS:
        continue
    overall = _titles(*data[0:5])
    overall_desc = _titles(*data[5:10])

    entry = {"overall": {"title": overall, "desc": overall_desc}}
    # Ensure Myanmar key exists in overall title and desc
    if not overall.get("my"):
        overall["my"] = overall.get("zh", "")
    if not overall_desc.get("my"):
        overall_desc["my"] = overall_desc.get("zh", "")

    if code in _FORTUNE_ZH:
        fdata_zh = _FORTUNE_ZH[code]
        fdata_en = _FORTUNE_EN.get(code, [""] * 5)
        fallback = _get_overall_translations(code)
        for i, fkey in enumerate(["love", "career", "wealth", "health", "travel"]):
            zh = fdata_zh[i]
            en = fdata_en[i] if i < len(fdata_en) else zh
            ja = fallback.get("ja", en)
            vi = fallback.get("vi", en)
            ko = fallback.get("ko", en)
            my = fallback.get("my", en) if fallback.get("my") else en  # Use en as Myanmar fallback
            entry[fkey] = {
                "title": _FORTUNE_TITLES[fkey],
                "desc": {"zh": zh, "ja": ja, "en": en, "vi": vi, "ko": ko, "my": my},
            }
    else:
        for fkey in ["love", "career", "wealth", "health", "travel"]:
            my_desc = overall_desc.get("zh", "")
            entry[fkey] = {"title": _FORTUNE_TITLES[fkey], "desc": {**overall_desc, "my": my_desc}}

    INTERPRETATIONS[code] = entry


GLOSSARY = {}
for lang, terms in _GLOSSARY.items():
    GLOSSARY[lang] = terms


# ===== Post-process: Add Myanmar to hexagrams 0-63 =====
_MY_NAMES_ALL = {
    0: "ကြွယ်ဝခြင်း", 1: "လက်ခံခြင်း", 2: "အခက်အခဲ", 3: "မိတ်ဆွေ",
    4: "စောင့်ဆိုင်းခြင်း", 5: "ပဋိပက္ခ", 6: "တပ်ဖွဲ့", 7: "ပူးပေါင်းခြင်း",
    8: "အသေးစား", 9: "လျှောက်လှမ်းခြင်း", 10: "ငြိမ်းချမ်းခြင်း", 11: "ငြိမ်သက်ခြင်း",
    12: "ရပ်တန့်ခြင်း", 13: "အဖွဲ့ဝင်ခြင်း", 14: "ကြီးကျယ်သည့်ပိုင်ဆိုင်မှု", 15: "ချိုသာခြင်း",
    16: "ပျော်ရွှင်ခြင်း", 17: "လိုက်လျောခြင်း", 18: "ပြုပြင်ခြင်း", 19: "ချဉ်းကပ်ခြင်း",
    20: "ဆင်ခြင်တုံတွေးခြင်း", 21: "ကျော်ဖြတ်ခြင်း", 22: "အလှပြင်ခြင်း",
    23: "ပြိုကျခြင်း", 24: "ပြန်လည်ထွက်ခြင်း", 25: "မထင်မှတ်ဘဲ", 26: "ကြီးကျယ်သည့်ထိန်းချုပ်မှု",
    27: "အစားအစာ", 28: "အလွန်ကြီးမားသည့်အတားအဆီး", 29: "ရေခံ", 30: "မီးလောင်ခြင်း",
    31: "ဆွဲဆောင်ခြင်း", 32: "ခိုင်မြဲခြင်း", 33: "ရှောင်ဖယ်ခြင်း", 34: "ကြီးကျယ်သည့်အင်အား",
    35: "တိုးတက်ခြင်း", 36: "မီးချောင်း", 37: "မိသားစု", 38: "ကွဲပြားခြင်း",
    39: "အတားအဆီး", 40: "ဖြေလျှောခြင်း", 41: "လျော့နည်းခြင်း", 42: "တိုးပွားခြင်း",
    43: "ဆုံးဖြတ်ချက်", 44: "ထိုးဖောက်ခြင်း", 45: "စုစည်းခြင်း", 46: "တက်တက်မြက်မြက်",
    47: "ညံ့ဖျင်းခြင်း", 48: "ရေတွင်း", 49: "ပြောင်းလဲခြင်း", 50: "အိုး",
    51: "မိုးကြိုးပစ်ခြင်း", 52: "ရပ်တန့်ခြင်း", 53: "ဖွံ့ဖြိုးခြင်း", 54: "အရွယ်ရောက်ခြင်း",
    55: "ကြွယ်ဝခြင်း", 56: "ခရီးသွားခြင်း", 57: "လေတိုက်ခြင်း", 58: "ပျော်ရွှင်ခြင်း",
    59: "ဖြိုဖျက်ခြင်း", 60: "ကန့်သတ်ခြင်း", 61: "ယုံကြည်ခြင်း", 62: "အသေးစားကျော်ဖြတ်ခြင်း",
    63: "ပြီးဆုံးခြင်း",
}
_MY_DESCS_ALL = {
    0: "ကြွယ်ဝခြင်းဗေဒသည် လုံးဝအမျိုးသားဓာတ်ဖြင့် ဖွဲ့စည်းထားပြီး သန်မာခြင်းနှင့် စွမ်းအင်ကို ကိုယ်စားပြုသည်။",
    1: "လက်ခံခြင်းဗေဒသည် နွဲ့နွဲ့ပျော့ပျောင်းခြင်းနှင့် လက်ခံခြင်းကို ကိုယ်စားပြုသည်။",
    2: "အခက်အခဲဗေဒသည် အစပျိုးခြင်း၏ အခက်အခဲကို ကိုယ်စားပြုသည်။",
    3: "မိတ်ဆွေဗေဒသည် အရွယ်ရောက်ခြင်းနှင့် မိတ်ဆွေဖွဲ့ခြင်းကို ကိုယ်စားပြုသည်။",
    4: "စောင့်ဆိုင်းခြင်းဗေဒသည် စောင့်ဆိုင်းခြင်း၏ ပညာရှိခြင်းကို သင်ကြားပေးသည်။",
    5: "ပဋိပက္ခဗေဒသည် ပဋိပက္ခနှင့် အငြင်းပွားမှုကို ကိုယ်စားပြုသည်။",
    6: "တပ်ဖွဲ့ဗေဒသည် အဖွဲ့အစည်းနှင့် စည်းကမ်းကို ကိုယ်စားပြုသည်။",
    7: "ပူးပေါင်းခြင်းဗေဒသည် ညီညွတ်မှုနှင့် ပူးပေါင်းဆောင်ရွက်ခြင်းကို ကိုယ်စားပြုသည်။",
    8: "အသေးစားဗေဒသည် အသေးစားစုဆောင်းမှုကို ကိုယ်စားပြုသည်။",
    9: "လျှောက်လှမ်းခြင်းဗေဒသည် သတိထားခြင်းကို သင်ကြားပေးသည်။",
    10: "ငြိမ်းချမ်းခြင်းဗေဒသည် ကြီးကျယ်သည့် ငြိမ်းချမ်းမှုကို ကိုယ်စားပြုသည်။",
    11: "ငြိမ်သက်ခြင်းဗေဒသည် ငြိမ်သက်ခြင်းနှင့် မလှုပ်ခြင်းကို ကိုယ်စားပြုသည်။",
    12: "ရပ်တန့်ခြင်းဗေဒသည် ရပ်တန့်ခြင်းကို ကိုယ်စားပြုသည်။",
    13: "အဖွဲ့ဝင်ခြင်းဗေဒသည် တူညီသည့်စိတ်ဓာတ်ရှိသူများ စုဝေးခြင်းကို ကိုယ်စားပြုသည်။",
    14: "ကြီးကျယ်သည့်ပိုင်ဆိုင်မှုဗေဒသည် ကြွယ်ဝခြင်းကို ကိုယ်စားပြုသည်။",
    15: "ချိုသာခြင်းဗေဒသည် ၆၄ ဗေဒအနက် အကောင်းဆုံးဖြစ်ပြီး ချိုသာခြင်းကို ကိုယ်စားပြုသည်။",
    16: "ပျော်ရွှင်ခြင်းဗေဒသည် ပျော်ရွှင်မှုနှင့် ပြင်ဆင်ခြင်းကို ကိုယ်စားပြုသည်။",
    17: "လိုက်လျောခြင်းဗေဒသည် လိုက်လျောခြင်းကို ကိုယ်စားပြုသည်။",
    18: "ပြုပြင်ခြင်းဗေဒသည် ပြုပြင်ရန် လိုအပ်ခြင်းကို ကိုယ်စားပြုသည်။",
    19: "ချဉ်းကပ်ခြင်းဗေဒသည် ချဉ်းကပ်လာခြင်းကို ကိုယ်စားပြုသည်။",
    20: "ဆင်ခြင်တုံတွေးခြင်းဗေဒသည် ဆင်ခြင်တုံတွေးခြင်းကို ကိုယ်စားပြုသည်။",
    21: "ကျော်ဖြတ်ခြင်းဗေဒသည် အတားအဆီးများကို ဖြတ်ကျော်ခြင်းကို ကိုယ်စားပြုသည်။",
    22: "အလှပြင်ခြင်းဗေဒသည် အလှပြင်ခြင်းကို ကိုယ်စားပြုသည်။",
    23: "ပြိုကျခြင်းဗေဒသည် ပြိုကျခြင်းနှင့် ဖြိုဖျက်ခြင်းကို ကိုယ်စားပြုသည်။",
    24: "ပြန်လည်ထွက်ခြင်းဗေဒသည် ပြန်လည်ထွက်ခြင်းနှင့် အသစ်ဖြစ်ပေါ်ခြင်းကို ကိုယ်စားပြုသည်။",
    25: "မထင်မှတ်ဘဲဗေဒသည် ရိုးသားမှုနှင့် သဘာဝအတိုင်းဖြစ်ပေါ်ခြင်းကို ကိုယ်စားပြုသည်။",
    26: "ကြီးကျယ်သည့်ထိန်းချုပ်မှုဗေဒသည် ကြီးကျယ်သည့်ထိန်းချုပ်မှုကို ကိုယ်စားပြုသည်။",
    27: "အစားအစာဗေဒသည် အစားအစာနှင့် ပြုစုခြင်းကို ကိုယ်စားပြုသည်။",
    28: "အလွန်ကြီးမားသည့်အတားအဆီးဗေဒသည် အလွန်ကြီးမားသည့်အတားအဆီးကို ကိုယ်စားပြုသည်။",
    29: "ရေခံဗေဒသည် ရေနှင့် အန္တရာယ်ကို ကိုယ်စားပြုသည်။",
    30: "မီးလောင်ခြင်းဗေဒသည် မီးနှင့် ထွန်းလင်းခြင်းကို ကိုယ်စားပြုသည်။",
    31: "ဆွဲဆောင်ခြင်းဗေဒသည် ဆွဲဆောင်မှုနှင့် သက်ရောက်မှုကို ကိုယ်စားပြုသည်။",
    32: "ခိုင်မြဲခြင်းဗေဒသည် ခိုင်မြဲခြင်းနှင့် တည်တံ့ခြင်းကို ကိုယ်စားပြုသည်။",
    33: "ရှောင်ဖယ်ခြင်းဗေဒသည် ရှောင်ဖယ်ခြင်းနှင့် ဆုတ်ခွာခြင်းကို ကိုယ်စားပြုသည်။",
    34: "ကြီးကျယ်သည့်အင်အားဗေဒသည် ကြီးကျယ်သည့်အင်အားကို ကိုယ်စားပြုသည်။",
    35: "တိုးတက်ခြင်းဗေဒသည် တိုးတက်ခြင်းနှင့် ရှေ့တိုးခြင်းကို ကိုယ်စားပြုသည်။",
    36: "မီးချောင်းဗေဒသည် မီးချောင်းခြင်းနှင့် မှောင်မိုက်ခြင်းကို ကိုယ်စားပြုသည်။",
    37: "မိသားစုဗေဒသည် မိသားစုနှင့် ဆက်ဆံရေးကို ကိုယ်စားပြုသည်။",
    38: "ကွဲပြားခြင်းဗေဒသည် ကွဲပြားခြင်းနှင့် ဆန့်ကျင်ဘက်ဖြစ်ခြင်းကို ကိုယ်စားပြုသည်။",
    39: "အတားအဆီးဗေဒသည် အတားအဆီးနှင့် ခက်ခဲခြင်းကို ကိုယ်စားပြုသည်။",
    40: "ဖြေလျှောခြင်းဗေဒသည် ဖြေလျှောခြင်းနှင့် လွတ်မြောက်ခြင်းကို ကိုယ်စားပြုသည်။",
    41: "လျော့နည်းခြင်းဗေဒသည် လျော့နည်းခြင်းကို ကိုယ်စားပြုသည်။",
    42: "တိုးပွားခြင်းဗေဒသည် တိုးပွားခြင်းကို ကိုယ်စားပြုသည်။",
    43: "ဆုံးဖြတ်ချက်ဗေဒသည် ဆုံးဖြတ်ချက်ချခြင်းကို ကိုယ်စားပြုသည်။",
    44: "ထိုးဖောက်ခြင်းဗေဒသည် ထိုးဖောက်ခြင်းကို ကိုယ်စားပြုသည်။",
    45: "စုစည်းခြင်းဗေဒသည် စုစည်းခြင်းကို ကိုယ်စားပြုသည်။",
    46: "တက်တက်မြက်မြက်ဗေဒသည် တက်တက်မြက်မြက်ဖြစ်ခြင်းကို ကိုယ်စားပြုသည်။",
    47: "ညံ့ဖျင်းခြင်းဗေဒသည် ညံ့ဖျင်းခြင်းကို ကိုယ်စားပြုသည်။",
    48: "ရေတွင်းဗေဒသည် ရေတွင်းနှင့် အရင်းအမြစ်ကို ကိုယ်စားပြုသည်။",
    49: "ပြောင်းလဲခြင်းဗေဒသည် ပြောင်းလဲခြင်းကို ကိုယ်စားပြုသည်။",
    50: "အိုးဗေဒသည် အိုးနှင့် အစားအစာပြုစုခြင်းကို ကိုယ်စားပြုသည်။",
    51: "မိုးကြိုးပစ်ခြင်းဗေဒသည် မိုးကြိုးပစ်ခြင်းနှင့် တုန်လှုပ်ခြင်းကို ကိုယ်စားပြုသည်။",
    52: "ရပ်တန့်ခြင်းဗေဒသည် ရပ်တန့်ခြင်းနှင့် တည်ငြိမ်ခြင်းကို ကိုယ်စားပြုသည်။",
    53: "ဖွံ့ဖြိုးခြင်းဗေဒသည် ဖွံ့ဖြိုးခြင်းနှင့် တိုးတက်ခြင်းကို ကိုယ်စားပြုသည်။",
    54: "အရွယ်ရောက်ခြင်းဗေဒသည် အရွယ်ရောက်ခြင်းကို ကိုယ်စားပြုသည်။",
    55: "ကြွယ်ဝခြင်းဗေဒသည် ကြွယ်ဝခြင်းကို ကိုယ်စားပြုသည်။",
    56: "ခရီးသွားခြင်းဗေဒသည် ခရီးသွားခြင်းကို ကိုယ်စားပြုသည်။",
    57: "လေတိုက်ခြင်းဗေဒသည် လေတိုက်ခြင်းကို ကိုယ်စားပြုသည်။",
    58: "ပျော်ရွှင်ခြင်းဗေဒသည် ပျော်ရွှင်ခြင်းကို ကိုယ်စားပြုသည်။",
    59: "ဖြိုဖျက်ခြင်းဗေဒသည် ဖြိုဖျက်ခြင်းကို ကိုယ်စားပြုသည်။",
    60: "ကန့်သတ်ခြင်းဗေဒသည် ကန့်သတ်ခြင်းကို ကိုယ်စားပြုသည်။",
    61: "ယုံကြည်ခြင်းဗေဒသည် ယုံကြည်ခြင်းကို ကိုယ်စားပြုသည်။",
    62: "အသေးစားကျော်ဖြတ်ခြင်းဗေဒသည် အသေးစားကျော်ဖြတ်ခြင်းကို ကိုယ်စားပြုသည်။",
    63: "ပြီးဆုံးခြင်းဗေဒသည် ပြီးဆုံးခြင်းကို ကိုယ်စားပြုသည်။",
}
for code in range(0, 64):
    if code in INTERPRETATIONS:
        entry = INTERPRETATIONS[code]
        my_name = _MY_NAMES_ALL.get(code, "")
        my_desc = _MY_DESCS_ALL.get(code, "")
        if my_name:
            entry["overall"]["title"]["my"] = my_name
        if my_desc:
            entry["overall"]["desc"]["my"] = my_desc
        for fkey in ["love", "career", "wealth", "health", "travel"]:
            if fkey in entry and "desc" in entry[fkey]:
                if not entry[fkey]["desc"].get("my"):
                    entry[fkey]["desc"]["my"] = my_desc or entry[fkey]["desc"].get("zh", "")


def get_hex_name(code):
    if code in INTERPRETATIONS:
        return INTERPRETATIONS[code]["overall"]["title"]
    return _titles("未知卦", "未知卦", "Unknown", "Không rõ", "미상", "အမည်မသိ")

def get_hex_meaning(code):
    if code in INTERPRETATIONS:
        return INTERPRETATIONS[code]["overall"]["desc"]
    return _titles("", "", "", "", "", "")
